### ISSUE TITLE
[core] Rename the ray.operator module

### ISSUE THREAD

**Issue by sumanthratna** [ray-project/ray#13635]
### Describe your feature request

`operator` is a standard Python module: https://docs.python.org/3/library/operator.html

when I try to run `python3.8 python/ray/setup-dev.py` from the root of the ray repo, importing argparse fails because Python looks into Ray's `operator` rather than the Python operator module. To solve this, the`operator` dir should be renamed to something like `ray_operator` (which is a bit redundant) to avoid `ImportError`s

(since this is a breaking change, we might want to do this through a deprecation warning first)

---
for the record, here's the full traceback of running `setup-dev`:
```
Traceback (most recent call last):
  File "python/ray/setup-dev.py", line 6, in <module>
    import argparse
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/argparse.py", line 88, in <module>
    import re as _re
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/re.py", line 127, in <module>
    import functools
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/functools.py", line 18, in <module>
    from collections import namedtuple
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/collections/__init__.py", line 21, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
ImportError: cannot import name 'itemgetter' from 'operator' (.../ray/python/ray/operator/__init__.py)
```
the issue also occurs if I run from within the `python` dir

**Comment by DmitriGekhtman** [comment]
Sorry about this. The offending PR is this one: https://github.com/ray-project/ray/pull/13392
For now, `setup-dev.py` still works from outside of  ray: `python ray/python/ray/setup-dev.py`.

**Comment by DmitriGekhtman** [comment]
I don't think this requires a deprecation warning -- the module is quite new.
