### ISSUE TITLE
Cannot build on Ubuntu 24.04 with conda-forge compilers

### ISSUE THREAD

**Issue by mattip** [ray-project/ray#56710]
When I try to build `master` on an x86_64 Ryzen machine with the gcc-13 installed via conda-forge, I get errors in compiling spdlog's vendored fmt library.
```
spdlog/fmt/bundled/core.h:1735:15: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
```

If I add `-Wno-error-dangling-reference` to move past that, I then see an error resolving `Record()`:
```
bazel-out/k8-fastbuild/bin/src/ray/raylet/_virtual_includes/lease_dependency_manager/ray/raylet/lease_dependency_manager.h:86:40: error: call of overloaded 'Record(int64_t&, <brace-enclosed initializer list>)' is ambiguous
   86 |           task_by_state_counter_.Record(
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
   87 |               num_inactive,
      |               ~~~~~~~~~~~~~             
   88 |               {{"State"sv,
      |               ~~~~~~~~~~~~              
   89 |                 rpc::TaskStatus_Name(rpc::TaskStatus::PENDING_OBJ_STORE_MEM_AVAIL)},
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   90 |                {"Name"sv, key.first},
      |                ~~~~~~~~~~~~~~~~~~~~~~   
   91 |                {"IsRetry"sv, key.second ? "1" : "0"},
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   92 |                {"Source"sv, "dependency_manager"}});
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/k8-fastbuild/bin/src/ray/observability/_virtual_includes/metric_interface/ray/observability/metric_interface.h:42:16: note: candidate: 'virtual void ray::observability::MetricInterface::Record(double, const std::unordered_map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&)'
   42 |   virtual void Record(double value,
      |                ^~~~~~
bazel-out/k8-fastbuild/bin/src/ray/observability/_virtual_includes/metric_interface/ray/observability/metric_interface.h:44:16: note: candidate: 'virtual void ray::observability::MetricInterface::Record(double, const std::unordered_map<std::basic_string_view<char>, std::__cxx11::basic_string<char> >&)'
```

This is with gcc 14.3, when running `bazel run //:gen_ray_pkg`.
```
$ gcc --version
gcc (Ubuntu 14.2.0-4ubuntu2~24.04) 14.2.0
```

**Comment by mattip** [comment]
`git bisect` points to #56015 for the problem resolving a correct overload for `Record()`, which makes sense since it touched these interfaces. I see compilation uses `-std=c++17` in `.bazelrc`, but maybe there is more needed to get the overloads to work on `gcc==14`? For completeness, here is the command used to compile, after removing all the include paths
<details><summary>compilation command split into lines on whitespace</summary>

```
/usr/bin/gcc
-U_FORTIFY_SOURCE
-fstack-protector
-Wall
-Wunused-but-set-parameter
-Wno-free-nonheap-object
-fno-omit-frame-pointer
-g0
-O2 '-D_FORTIFY_SOURCE=1'
-DNDEBUG
-ffunction-sections
-fdata-sections '-std=c++14'
-MD
-MF <path>/lease_dependency_manager.d 
-frandom-seed=<path>/lease_dependency_managerlease_dependency_manager.o'
-DBOOST_NO_CXX98_FUNCTION_BASE
-DHAVE_ABSEIL 
-DOPENTELEMETRY_STL_VERSION=(__cplusplus/100)
-DOPENTELEMETRY_ABI_VERSION_NO=1
-DCARES_STATICLIB
-DBOOST_ASIO_SEPARATE_COMPILATION 
-DBAZEL_CURRENT_REPOSITORY=""
-fPIC 
-std=c++17
-DBAZEL_OPT
-Wunused-result
-Wconversion-null
-Wno-misleading-indentation
-Wimplicit-fallthrough
-Wshadow
-Werror 
-Wno-error=dangling-reference
-fno-canonical-system-headers
-Wno-builtin-macro-redefined
-D__DATE__="redacted"
-D__TIMESTAMP__="redacted"
-D__TIME__="redacted"
-c src/ray/raylet/lease_dependency_manager.cc
-o bazel-out/k8-opt/bin/src/ray/raylet/_objs/lease_dependency_manager/lease_dependency_manager.o
```

</details>

**Comment by mattip** [comment]
Fixed by #56514, thanks @dayshah
