### PR TITLE
[tune] update Optuna integration to 2.4.0 API

### LINKED ISSUE #13622: [tune] AttributeError: 'InMemoryStorage' object has no attribute 'set_trial_value' - Optuna
Brief setup:
```
tuning_objective = 'loss_valid'
suggest = OptunaSearch()
suggest = ConcurrencyLimiter(suggest, max_concurrent=4)
schedule = AsyncHyperBandScheduler() 
reporter = tune.CLIReporter()
parameter_columns=[...]
metric_columns=[...]
for param in parameter_columns:
    reporter.add_parameter_column(param)
for metric in metric_columns:
    reporter.add_metric_column(metric)
analysis = tune.run(runner,
				metric=tuning_objective,
				mode='min',
				search_alg=suggest,
				scheduler=schedule,
				resources_per_trial={'cpu': 1, 'gpu': 1}, 
				num_samples=100, 
				config=config,
				local_dir='./ray_results',
				progress_reporter=reporter,
				keep_checkpoints_num=3,
				checkpoint_score_attr='min-'+str(tuning_objective),
				)
```

This error occurs after the first trial is complete (`done: true`):
> File "/home/user/anaconda3/envs/user/lib/python3.7/site-packages/ray/tune/suggest/optuna.py", line 211, in on_trial_complete
>     self._storage.set_trial_value(ot_trial_id, result.get(
> AttributeError: 'InMemoryStorage' object has no attribute 'set_trial_value'

### PR DESCRIPTION
**Pull request by krfricke**
## Why are these changes needed?

Optuna break after updating to 2.4.0 - this adapts to the new API.

## Related issue number

Closes #13622

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by amogkam — APPROVED** [review]
LGTM!

**Comment by krfricke** [comment]
The failing tests seem unrelated to this PR. I'm rerunning them anyway and will check tomorrow.
