### ISSUE TITLE
[CI] `linux://python/ray/tune:test_tune_restore` is failing/flaky on master.

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#38028]
- 50e4d4cd1126f26f7497485d0dc2bef9b9c5209a FAILED [Buildkite :octopus: :brain: :last_quarter_moon_with_face: Old execution path: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5243#0189b78c-c9d6-47bd-9bc7-de2e25132704)
- 50e4d4cd1126f26f7497485d0dc2bef9b9c5209a FAILED [Buildkite :octopus: :brain: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5243#0189b78c-c9ca-4911-8e2a-c229122cbae2)
- f19e0279da8ca9083ad82fc066db2caf9a67bb06 FAILED [Buildkite :octopus: :brain: :last_quarter_moon_with_face: Old execution path: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5242#0189b78c-d796-4cfe-ac5e-2e212a3da53c)
- f19e0279da8ca9083ad82fc066db2caf9a67bb06 FAILED [Buildkite :octopus: :brain: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5242#0189b78c-d78a-4540-a05f-2be725b57054)
- 25cf1842da5fab09466b5e548b0214b6bd8e750f FAILED [Buildkite :octopus: :brain: :last_quarter_moon_with_face: Old execution path: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5241#0189b744-2f97-4af2-b6bc-65381ec1b79f)
- 25cf1842da5fab09466b5e548b0214b6bd8e750f FAILED [Buildkite :octopus: :brain: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5241#0189b744-2f8d-4805-b43f-4763598eba67)
- 67945d078942c99e859d97eef5c6e3aa6b132283 FAILED [Buildkite :octopus: :brain: :last_quarter_moon_with_face: Old execution path: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5240#0189b725-0b4a-482d-ad14-430d1a21f59f)
- 67945d078942c99e859d97eef5c6e3aa6b132283 FAILED [Buildkite :octopus: :brain: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5240#0189b725-0b3e-4537-86b1-92ec5a2c9a16)
- 1618345acebaad18d18d34e5599c553096181e81 FAILED [Buildkite :octopus: :brain: :last_quarter_moon_with_face: Old execution path: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5239#0189b71c-8a3f-4179-90ad-788bafa3051d)
- 1618345acebaad18d18d34e5599c553096181e81 FAILED [Buildkite :octopus: :brain: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5239#0189b71c-8a2e-4515-9ba1-be963aa540f0)
- 4fe33b513b4367fdd0e341206c7e64dd4b622c6e FAILED [Buildkite :octopus: :brain: :last_quarter_moon_with_face: Old execution path: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5238#0189b705-bef5-4b79-b700-7baf705ad458)
- 4fe33b513b4367fdd0e341206c7e64dd4b622c6e FAILED [Buildkite :octopus: :brain: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5238#0189b705-beec-4f0b-837b-b204bd437d32)
- a2aa27e95df83db4cfda7fc77c463f09c26489d9 FAILED [Buildkite :octopus: :brain: :last_quarter_moon_with_face: Old execution path: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5237#0189b6da-1d62-41ff-93e3-e3dc8e336a2f)
- a2aa27e95df83db4cfda7fc77c463f09c26489d9 FAILED [Buildkite :octopus: :brain: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5237#0189b6da-1d57-4338-95bc-79ae623e09c5)
- 48488f50de39a9d7ef51094b5c5eefabee3ba08c FAILED [Buildkite :octopus: :brain: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5236#0189b629-4a4c-4628-aac7-20e7c2fcf17a)
- 48488f50de39a9d7ef51094b5c5eefabee3ba08c FAILED [Buildkite :octopus: :brain: :last_quarter_moon_with_face: Old execution path: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5236#0189b629-4a58-427f-8f91-f21c8ab7a02b)
- e8db5da958e0db83d19eecf00a4886e280295d13 FAILED [Buildkite :octopus: :brain: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5185#018999f1-6cd0-4c46-b798-bcfb215c3ed4)
- 9bf15e806d3518d45d40546c641fcacd3a87618d FAILED [Buildkite :octopus: :brain: Tune tests and examples {using RLlib}](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5183#01899984-6323-459c-b788-ca376e8cf71b)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/tune:test_tune_restore-END
....

**Comment by xwjiang2010** [comment]
ImportError: cannot import name '__warningregistry__' from 'supersuit'

**Comment by xwjiang2010** [comment]
offending PR reverted by https://github.com/ray-project/ray/pull/38035
