### ISSUE TITLE
[Bug]  AttributeError: 'env' object has no attribute '_agent_ids' after updating from 1.6 to 1.11

### ISSUE THREAD

**Issue by richielo** [ray-project/ray#23531]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

I am tackling multi-agent RL problems in multi-grid (multi-agent's extension of minigrid). After upgrading to the latest version of Ray, I receive the titled error in /ray/rllib/env/multi_agent_env.py

### Versions / Dependencies

Python == 3.9
Ray == 1.11

### Reproduction script

This is my configuration 

```
config = {
        "framework": "torch", #I could use tensorflow by passing "tf" or "tf2"
        "env": "test_env", 
        "num_workers": 3,
        "num_gpus": 1, #gpus to use
        "model" : {"custom_model":"pa_model"},
        "multiagent": {
            "policies": {
                "high_level_policy": (None, Dict({'observations' : Box(low=0, high=255, shape=(42, 42, 6 + num_tasks_per_agent), dtype='uint8'), 'tasks' : Box(low=0, high=10000, shape=(num_tasks * 5, 1), dtype=np.float32), 'action_mask' : MultiBinary(num_tasks + 1)}),
                                      Discrete(num_tasks + 1), {"gamma": 1,
                                      }),
            },
            "policies_to_train": ["high_level_policy"],
            "policy_mapping_fn": policy_mapping_fn,
        },
    }
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by gjoliver** [comment]
likely related case: https://github.com/ray-project/ray/issues/22943

**Comment by sortiz-hub** [comment]
Hi all,

Same happened to me with Python 3.7 and Ray 1.12.0 - in Ubuntu.
No issue with Python 3.7 and Ray 1.10.0 in Windows.

**Comment by sven1977** [comment]
Closing this one here as a dupe of this issue here, which has a working repro script:
https://github.com/ray-project/ray/issues/22943
