### ISSUE TITLE
Custom RLLib Algorithm get_default_policy_class method erroring

### ISSUE THREAD

**Issue by everythingeverywhereao** [ray-project/ray#33452]
### What happened + What you expected to happen

I have implemented a subclass of the RLLib PPOTorch algorithm, and after upgrading my Ray version from 2.1.0 to 2.3.0, I noticed a bug while simply initializing my trainer like this:

`Trainer = CustomPPO(
            config,
            logger_creator=build_logger_creator(log_dir, experiment_name),
        )`

I am seeing the following error log:

> Traceback (most recent call last):
>   File "/home/.local/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
>     return self.run(
>   File "/home/.local/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
>     run()
>   File "/home/.local/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
>     self.result = self.main_function(*args)
>   File "/home/.local/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
>     result = wrapped(*args, **kwargs)
>   File "/home/occupancy-measure-anomaly-detection/occupancy_measures/experiments/experiments.py", line 198, in main
>     trainer = CustomPPO(
>   File "/home/.local/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 371, in __init__
>     config.validate()
>   File "/home/.local/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm_config.py", line 820, in validate
>     default_policy_cls = self.algo_class.get_default_policy_class(self)
> TypeError: get_default_policy_class() missing 1 required positional argument: 'config'
            
If I remove the config parameter from the method in question, I receive the following error: 

>  File "/home/.local/lib/python3.8/site-packages/ray/rllib/algorithms/algorithm.py", line 574, in setup
>     default_policy_class=self.get_default_policy_class(self.config),
> TypeError: get_default_policy_class() takes 1 positional argument but 2 were given

### Versions / Dependencies

python version: 3.8 (but it also seems to error on 3.9 and 3.10 for me
Ray: 2.3.0

### Reproduction script

My `get_default_policy_class` method is defined like this:

def get_default_policy_class(self, config: TrainerConfigDict) -> Type[Policy]:

        if config["framework"] == "torch":
            return CustomPPOPolicy
        else:
            raise NotImplementedError()

### Issue Severity

High: It blocks me from completing my task.

**Comment by kouroshHakha** [comment]
`get_default_policy_class` should be class method. You have defined it as an instance method.
