### ISSUE TITLE
Fail to run the demo in hyperopt_example.py

### ISSUE THREAD

**Issue by guvcolie** [ray-project/ray#8031]
System information
   OS Platform and Distribution: Ubuntu 16.04
   Ray installed from (source or binary): pip3 install ray
   Ray version: 0.8.4  latest
   Python version: 3.6
   Exact command to reproduce: copy this code https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/hyperopt_example.py , then run this code.

Describe the problem

When I use the hyperopt_example, a error is reported as below:
2020-04-15 17:55:06,162	ERROR trial_executor.py:64 -- Trial easy_objective_2f09bfb6: Error checkpointing trial metadata.
Traceback (most recent call last):
  File "/home/lijixiang/anaconda3/lib/python3.6/site-packages/ray/tune/trial_executor.py", line 61, in try_checkpoint_metadata
    self._cached_trial_state[trial.trial_id] = trial.__getstate__()
  File "/home/lijixiang/anaconda3/lib/python3.6/site-packages/ray/tune/trial.py", line 551, in __getstate__
    self.result_logger.flush(sync_down=False)
  File "/home/lijixiang/anaconda3/lib/python3.6/site-packages/ray/tune/logger.py", line 330, in flush
    _logger.flush()
  File "/home/lijixiang/anaconda3/lib/python3.6/site-packages/ray/tune/logger.py", line 237, in flush
    self._file_writer.flush()
AttributeError: 'SummaryWriter' object has no attribute 'flush'

**Comment by rkooo567** [comment]
@richard4912 maybe there were api changes?

**Comment by guvcolie** [comment]
sorry, my fault ...
my tensorboardX's version was 1.6, it's too old. After updating to v2.0, everything is OK! 
thank you!
