### PR TITLE
[core] Fixing windows build with cgroups. Broken in cgroups 10/n.

### PR DESCRIPTION
**Pull request by israbbani**
Broken in #56446. 

This should stop being possible once there's a single cgroups target exported (as highlighted in #54703). 

I've fixed the broken build and I've added a temporary test target that builds the noop implementations as part of Linux CI so it gets caught in premerge.

### CODE REVIEW

File: src/ray/common/cgroup2/BUILD.bazel [hunk 1]
```diff
@@ -79,7 +79,33 @@ ray_cc_library(
...
 )
 
-# Private Targets.
+# Private targets
+#
+# TODO(#54703): This target builds the noop implementations.
+# There's a corressponding test that runs on Linux and Non-Linux
+# CI so breakages are caught in premerge before these targets are
+# cleaned up at the end of the resource isolation milestone 1
+# project.
```
Comment (jjyao) [inline src/ray/common/cgroup2/BUILD.bazel:88]: I feel we don't really need this given we are very close to remove the noop thing and I'm sure you won't miss it anymore.

**Review by jjyao — APPROVED** [review]

File: src/ray/common/cgroup2/BUILD.bazel (hunk 1 above)
Comment (israbbani) [reply src/ray/common/cgroup2/BUILD.bazel:88]: I plan on deleting this in a few more PRs. I added it so I don't accidentally break CI again with 11/n and 12/n.

**Comment by jjyao** [comment]
Windows compilation errors.

**Comment by israbbani** [comment]
> Windows compilation errors.

Unrelated. @Sparks0219 is looking into those. They're from the FakeRayClient. 

The python failure on windows is from
```
[2025-09-17 22:09:20,481 C 14892 16076] (raylet.exe) dlmalloc.cc:128:  An unexpected system state has occurred. You have likely discovered a bug in Ray. Please report this issue at https://github.com/ray-project/ray/issues and we'll work with you to fix it. Check failed: *handle != nullptr CreateFileMapping() failed. GetLastError() = 1450
*** StackTrace Information ***
```

**Comment by edoakes** [comment]
trusting that compilation errors are unrelated
