### PR TITLE
[client] Fix credential generation when secure=True but no credentials provided

### LINKED ISSUE #18633: [Nightly Release] AttributeError: 'Worker' object has no attribute '_credentials'
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Nightly release tests are broken by 
AttributeError: 'Worker' object has no attribute '_credentials' 

https://buildkite.com/ray-project/periodic-ci/builds/987#178c69a0-23d1-43d5-b172-1b0b0667d528

### Reproduction script

https://buildkite.com/ray-project/periodic-ci/builds/987#178c69a0-23d1-43d5-b172-1b0b0667d528

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ckw017**
## Why are these changes needed?

Credential gen was broken by #18484 if secure was set but _credentials isn't passed. Added a test to prevent future regressions

## Related issue number

Closes #18633

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by Yard1 — APPROVED** [review]

**Comment by Yard1** [comment]
Merging master should fix lint

**Review by AmeerHajAli — APPROVED** [review]

File: python/ray/util/client/worker.py [hunk 1]
```diff
@@ -105,6 +105,8 @@ def __init__(
         if _credentials is not None:
```
Comment (sasha-s) [inline python/ray/util/client/worker.py:105]: we could have
```
self._credentials = _credentials
if _credentials is not None:
         self._secure = True
```
fine either way

**Review by sasha-s — APPROVED** [review]

**Comment by ckw017** [comment]
Good to merge. Failures are:
- linux: run_regression_tests_cartpole_continuous_pybullet_sac_tf
- linux: run_regression_tests_stateless_cartpole_r2d2_tf
- windows: test_placement_group_2   
- windows: test_placement_group_3
- windows: test_mini_placement_group

All of which are flaky on master atm
Screen Shot 2021-09-15 at 2 28 29 PM
