### ISSUE TITLE
RayDP: Hive Metastore not working

### ISSUE THREAD

**Issue by raviranak** [ray-project/ray#35876]
### What happened + What you expected to happen

Hive Metastore not working with raydp on Spark 3.3.1 

### Versions / Dependencies

ray runtime 2.3.0 , spark 3.3.1 , mysql:mysql-connector-java:8.0.32

### Reproduction script

Code setup 
```
import raydp
default_spark_conf = {
"spark.jars.packages": "mysql:mysql-connector-java:8.0.32",
"spark.jars": "/home/ray/.ivy2/jars/com.mysql_mysql-connector-j-8.0.32.jar ,/home/ray/.ivy2/jars/com.google.protobuf_protobuf-java-3.21.9.jar",
"spark.hadoop.javax.jdo.option.ConnectionDriverName": "com.mysql.jdbc.Driver",
"spark.hadoop.javax.jdo.option.ConnectionURL": "<url>",
"spark.hadoop.javax.jdo.option.ConnectionUserName": "<uid>",
"spark.hadoop.javax.jdo.option.ConnectionPassword": "<pass>",
"spark.sql.catalog.spark_catalog.type":"hive",
"spark.sql.catalogImplementation":"hive"
}
spark = raydp.init_spark(
app_name="Darwin_SPARK",
num_executors=2,
executor_cores=4,
executor_memory='4G',
enable_hive= True,
configs=default_spark_conf)
```

Running spark.run("show tables") throw exception 
`2023-05-30 01:22:35,847 WARN HiveMetaStore [Thread-5]: Retrying creating default database after error: Unexpected exception caught.
javax.jdo.JDOFatalInternalException: Unexpected exception caught.
	at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1203) ~[javax.jdo-3.2.0-m3.jar:?]
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:814) ~[javax.jdo-3.2.0-m3.jar:?]
	at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:702) ~[javax.jdo-3.2.0-m3.jar:?]

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.datanucleus.util.NucleusLogger
	at org.datanucleus.plugin.PluginRegistryFactory.newPluginRegistry(PluginRegistryFactory.java:58)
	at org.datanucleus.plugin.PluginManager.<init>(PluginManager.java:60)`

While on other hand doing same with pyspark SparkSession its working 

`
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Spark Examples") \
.config("spark.hadoop.javax.jdo.option.ConnectionURL", "<url>") \
.config("spark.hadoop.javax.jdo.option.ConnectionDriverName", "com.mysql.cj.jdbc.Driver") \
.config("spark.hadoop.javax.jdo.option.ConnectionUserName", "<uid>") \
.config("spark.hadoop.javax.jdo.option.ConnectionPassword", "<pass>") \
.config("spark.sql.catalogImplementation","hive") \
.config("spark.sql.catalog.spark_catalog.type","hive") \
.config("spark.jars","/home/ray/.ivy2/jars/com.mysql_mysql-connector-j-8.0.32.jar") \
.config("spark.jars.packages", "mysql:mysql-connector-java:8.0.32") \
.enableHiveSupport().getOrCreate()

spark.show("show tables")
`

### Issue Severity

High: It blocks me from completing my task.
