### PR TITLE
Check the existence of __version__ in pydantic before use

### PR DESCRIPTION
**Pull request by jrosti**
## Why are these changes needed?

Pydantic_2 checks introduced incompatibility with pydantic < 1.9.0. In older versions the `__version__` -attribute was missing from pydantic, and the checks caused immediate exception in all `ray` command executions:

```
% pip install pydantic==1.8.1
Successfully installed pydantic-1.8.1
(ray-fix) jrosti@pai ray % python -c 'import ray.util.state.common'                 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jrosti/.pyenv/versions/ray-fix/lib/python3.9/site-packages/ray/util/state/__init__.py", line 1, in <module>
    from ray.util.state.api import (
  File "/Users/jrosti/.pyenv/versions/ray-fix/lib/python3.9/site-packages/ray/util/state/api.py", line 17, in <module>
    from ray.util.state.common import (
  File "/Users/jrosti/.pyenv/versions/ray-fix/lib/python3.9/site-packages/ray/util/state/common.py", line 38, in <module>
    is_pydantic_2 = pydantic.__version__.startswith("2")
AttributeError: module 'pydantic' has no attribute '__version__'
```

## Related issue number

PR is discussed here:

https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1691663217273319
with  @richardliaw

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [x] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested :(
   
   Tested manually that the fix works with Pydantic 1.8.*.  Expecting the functionality to be covered by current unit tests.

### CODE REVIEW

**Review by alanwguo — APPROVED** [review]

**Comment by alanwguo** [comment]
@jrosti, thanks for your contribution!

@rkooo567 , ptal for merging.

**Comment by rkooo567** [comment]
Failed tests seem unrelated
