### ISSUE TITLE
bad warning - AttributeError: 'NoneType' object has no attribute 'global_worker'

### ISSUE THREAD

**Issue by PovelikinRostislav** [ray-project/ray#8003]
### What is the problem?
After launching the dcgan sample on local machine, the sample finishes all epochs and failed with the following log from each worker:
```
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
```

Full log:
```
$ python dcgan.py --num-workers 44
2020-04-13 16:48:16,768 INFO resource_spec.py:204 -- Starting Ray with 120.17 GiB memory available for workers and up to 55.5 GiB for objects. You can adjust these settings with ray.init(mem
ory=<bytes>, object_store_memory=<bytes>).
2020-04-13 16:48:17,201 INFO services.py:1146 -- View the Ray dashboard at localhost:8265
  num_samples    epoch    batch_count    loss_g    last_loss_g    loss_d    last_loss_d    inception    last_inception
-------------  -------  -------------  --------  -------------  --------  -------------  -----------  ----------------
        60016        1            124   2.50279        2.34154   1.69439        1.71655      1.85531           2.09533
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [01:17<00:00, 77.08s/epoch, loss_g=2.5, loss_d=1.69]
1/1e: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 124/124 [01:17<00:00,  1.61batch/sE
xception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x7fc8e9ffae50>
Traceback (most recent call last):
  File "/rpovelik/installed/miniconda3/envs/ray/lib/python3.8/site-packages/ray/actor.py", line 657, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
```
*Ray version and other system information (Python version, TensorFlow version, OS):*
ray 0.8.4
Torch 1.4.0
Ubuntu 18.04
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

`$ python dcgan.py --num-workers 44`

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

**Comment by rkooo567** [comment]
@edoakes This looks more like a core bug happening from python 3.8? I assume the global variable global_worker is cleaned earlier than the actor handle is exited. Have you seen this before?

Also, @PovelikinRostislav, is it happening when you use Python 3.7 as well?

**Comment by m3at** [comment]
I have a similar error so I made a minimal reproducible example, sharing in case it's helpful:

```python
import ray
import torch  # if torch is imported crash, otherwise run fine

@ray.remote
def f(shard):
    print(f"{shard}")

ray.init(include_webui=False)

# Work in 3.8 and 3.7
ray.get(
    [
        f.remote(shard)
        for shard in ray.util.iter.from_range(10, num_shards=4, repeat=True).shards()
    ]
)

# Crash in 3.8 but not 3.7
it = ray.util.iter.from_range(10, num_shards=4, repeat=True).shards()
ray.get([f.remote(shard) for shard in it])
```
Tested in docker with base images {`python:3.8.2`, `python:3.7.7`}.  
So this fail only with the combination of `pytorch`+`list comprehension`. This seem very specific, I'm not sure if it's an issue coming from Ray.

**Comment by davidia** [comment]
I'm seeing this in python 3.8.3 with  ray 0.8.7 and not using Torch.

**Comment by dg4271** [comment]
Is this issue solved? I struggling with same issue

```python
import ray
from ray import serve
from fairseq.models.transformer import TransformerModel
import requests

class FairseqModel:
    def __init__(self):
        self.model = TransformerModel.from_pretrained("""My model""")
    def __call__(self, request):        
        return self.model.translate(str(request.json["data"]))

ray.init()
client = serve.start(http_host="0.0.0.0", detached=True)

client.create_backend("fairseq_model", FairseqModel)
client.create_endpoint(
    "my_endpoint",
    backend="fairseq_model",
    route="/translate",
    methods=["POST"])

# Query it!
sample_request_input = {"data": "sample input"}
response = requests.post("http://0.0.0.0:8000/translate", json=sample_request_input)
print(response.text)
```

Full log
```
2021-02-03 06:10:43,121 INFO services.py:1090 -- View the Ray dashboard at http://127.0.0.1:8265
2021-02-03 06:10:43,125 WARNING services.py:1552 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67104768 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
(pid=23234) 2021-02-03 06:10:44,630     INFO controller.py:191 -- Starting router with name 'SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-node:172.17.0.5-0' on node 'node:172.17.0.5-0' listening on '0.0.0.0:8000'
(pid=23253) 2021-02-03 06:10:44,766     WARNING worker.py:1428 -- Using blocking ray.get inside async actor. This blocks the event loop. Please use `await` on object ref with asyncio.gather if you want to yield execution to the event loop instead.
(pid=23253) INFO:     Started server process [23253]
(pid=23243) normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
(pid=23234) 2021-02-03 06:10:50,393     INFO controller.py:702 -- Registering route '/translate' to endpoint 'my_endpoint' with methods '['POST']'.
#translation of sample input
Exception ignored in: <function ActorHandle.__del__ at 0x7efc3083d0d0>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/ray/actor.py", line 753, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'

```

Ray version and other system information (Python version, TensorFlow version, OS):
ray 1.1.0
fairseq 0.10.2
python 3.8.3
Ubuntu 18.0.4

**Comment by rkooo567** [comment]
Cc @richardliaw

**Comment by Tomas0413** [comment]
I also noticed that I'm getting the same error. It doesn't affect me much, but I was curious about it. This is what I see (running only a single worker):

```
Exception ignored in: <function ActorHandle.__del__ at 0x7f836bca8a60>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/ray/actor.py", line 796, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
```

```
Python 3.8.5

Name: ray
Version: 2.0.0.dev0
```

**Comment by richardliaw** [comment]
Yeah this is a harmless error. However, it is misleading and is due to a race condition on our side.

**Comment by email2liyang** [comment]
I can reproduce this in Python 3.8.6   and ray 1.4.0 with simple code like below
```
import ray

ray.init()


@ray.remote
class Counter(object):
    def __init__(self):
        self.n = 0

    def increase(self):
        self.n += 1

    def read(self):
        return self.n


counters = [Counter.remote() for i in range(4)]
[c.increase.remote() for c in counters]
futures = [c.read.remote() for c in counters]

print(ray.get(futures))

```

log below
```
Exception ignored in: <function ActorHandle.__del__ at 0x114c71a60>
Traceback (most recent call last):
  File "/Users/ivan/.pyenv/versions/ray-side/lib/python3.8/site-packages/ray/actor.py", line 823, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x114c71a60>
Traceback (most recent call last):
  File "/Users/ivan/.pyenv/versions/ray-side/lib/python3.8/site-packages/ray/actor.py", line 823, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x114c71a60>
Traceback (most recent call last):
  File "/Users/ivan/.pyenv/versions/ray-side/lib/python3.8/site-packages/ray/actor.py", line 823, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
Exception ignored in: <function ActorHandle.__del__ at 0x114c71a60>
Traceback (most recent call last):
  File "/Users/ivan/.pyenv/versions/ray-side/lib/python3.8/site-packages/ray/actor.py", line 823, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'
```

**Comment by linpan** [comment]
centos 7.5 python3.8.7   I have the same issues, again. sucks.

**Comment by rkooo567** [comment]
Hmm yeah I failed to repro on macOS… can you verify if the above script can repro ur issues on centOS @linpan?

**Comment by hopdino** [comment]
@rkooo567  where is scripts ?   To far,   ray is unstable, too bugs.   not use production

**Comment by DLWCMD** [comment]
I can reproduce in the following environment:

- macOS 11.4
- Ray 1.3
- Python 3.8.8

My use case is evaluating a restored rllib PPO agent with the while not done construct:

```
while not done:
	action = agent.compute_action(obs)
	obs, reward, done, info = env.step(action)
    	step += 1
    	episode_reward += reward
print('Episode reward: {0:4.2f}'.format(episode_reward))
print('Step: {0:4d}'.format(int(step)))```

Interestingly, the two final print statements are executed before the error is reported. 
Also, the process finishes with exit code 0, so apparently the error is not fatal, as previously suggested.

Script attached. Note this is based on Ray tune and rllib examples.
[RLlib_RestoreChp_1.py.zip](https://github.com/ray-project/ray/files/6682703/RLlib_RestoreChp_1.py.zip)

**Comment by xiuxiu** [comment]
I can reproduce in the following environment:

ubuntu 18.04
Ray 1.4.1
Python 3.8.10

Sample code
`import ray
ray.init()

@ray.remote
class Counter(object):
    def __init__(self):
        self.n = 0

    def increment(self):
        self.n += 1

    def read(self):
        return self.n

counters = [Counter.remote() for i in range(4)]
[c.increment.remote() for c in counters]
futures = [c.read.remote() for c in counters]
print(ray.get(futures))`

**Comment by linpan** [comment]
use ray2.0dev try again



At 2021-07-02 19:12:52, "Rock Luo" ***@***.***> wrote:

I can reproduce in the following environment:

ubuntu 18.04
Ray 1.4.1
Python 3.8.10

Sample code
`import ray
ray.init()

@ray.remote
class Counter(object):
def init(self):
self.n = 0

def increment(self):
    self.n += 1

def read(self):
    return self.n


counters = [Counter.remote() for i in range(4)]
[c.increment.remote() for c in counters]
futures = [c.read.remote() for c in counters]
print(ray.get(futures))`

**Comment by imxuemei** [comment]
I can reproduce in the following environment:
OS: win 10
python: 3.8
ray: 2.0 dev

The code is from https://github.com/ray-project/ray/blob/master/rllib/agents/maml/tests/test_maml.py, and I modify it as follows.
`ray.init(include_dashboard=False)
# TestMAML().test_maml_compilation()
config = maml.DEFAULT_CONFIG.copy()
config["framework"] = "torch"
config["num_workers"] = 1
config["horizon"] = 200
env_ = "ray.rllib.examples.env.cartpole_mass.CartPoleMassEnv"
num_iterations = 1
trainer = maml.MAMLTrainer(config=config, env=env_)
for i in range(num_iterations):
    trainer.train()
# check_compute_single_action(trainer, include_prev_action_reward=True)
# trainer.stop()
ray.shutdown()`

The error log is as follows.
> 2021-07-04 22:36:43,049	INFO trainer.py:714 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2021-07-04 22:36:45,975	WARNING util.py:55 -- Install gputil for GPU system monitoring.
Exception ignored in: <function ActorHandle.__del__ at 0x0000022B46364820>
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\rayenv\lib\site-packages\ray\actor.py", line 834, in __del__
AttributeError: 'NoneType' object has no attribute 'global_worker'

**Comment by linpan** [comment]
so weird bugs



At 2021-07-04 22:44:06, "imxuemei" ***@***.***> wrote:

I can reproduce in the following environment:
OS: win 10
python: 3.8
ray: 2.0 dev

The code is from https://github.com/ray-project/ray/blob/master/rllib/agents/maml/tests/test_maml.py, and I modify it as follows.
`ray.init(include_dashboard=False)

TestMAML().test_maml_compilation()

config = maml.DEFAULT_CONFIG.copy()
config["framework"] = "torch"
config["num_workers"] = 1
config["horizon"] = 200
env_ = "ray.rllib.examples.env.cartpole_mass.CartPoleMassEnv"
num_iterations = 1
trainer = maml.MAMLTrainer(config=config, env=env_)
for i in range(num_iterations):
trainer.train()

check_compute_single_action(trainer, include_prev_action_reward=True)
trainer.stop()

ray.shutdown()`

The error log is as follows.

2021-07-04 22:36:43,049 INFO trainer.py:714 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
2021-07-04 22:36:45,975 WARNING util.py:55 -- Install gputil for GPU system monitoring.
Exception ignored in: <function ActorHandle.del at 0x0000022B46364820>
Traceback (most recent call last):
File "E:\ProgramData\Anaconda3\envs\rayenv\lib\site-packages\ray\actor.py", line 834, in del
AttributeError: 'NoneType' object has no attribute 'global_worker'

**Comment by ericl** [comment]
Duplicates https://github.com/ray-project/ray/issues/16947

**Comment by llango** [comment]
这个不影响， 直接注释ray包下actor.py 第816-822 便可以去掉这个错误。
