### ISSUE TITLE
[RLlib] Gymnasium integration

### ISSUE THREAD

**Issue by PieroMacaluso** [ray-project/ray#29697]
### Description

Yesterday, 25th October, Farama Foundations announced [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) (see [article](https://farama.org/Announcing-The-Farama-Foundation)), the official heir of OpenAI Gym. The integration would have been straightforward from the Gym 0.26.2 version as reported in the article with just `import gymnasium as gym`

Unfortunately RLlib still depends on `gym<0.24.1,>=0.21.0`.

It would be very useful to have this kind of integration since with high-probability `gymnasium` will attract much attention from the RL Open Source community.

**Comment by richardliaw** [comment]
cc @avnishn , @peytondmurray, @sven1977 

We should get this into the next release.

**Comment by alexxcollins** [comment]
do you have any update on this? I have seen comments relating to gymnasium compatibility in the ray and rllib code.

In the meantime can you suggest a hack to enable using gymnasium? For instance I want to use the minigrid library (https://github.com/Farama-Foundation/MiniGrid) also maintained by the Farama Foundation, but running `ray.rllib.utils.pre_checks.env.check_env()` fails.

(I'm using ray 2.1.0 on Apple silicon)

**Comment by sven1977** [comment]
Hey everyone (@PieroMacaluso , @peytondmurray , @maziarg , @alexxcollins ), update on the #28369 PR:
* We are very close to finishing this.
* Only outstanding items are running our release tests (Atari and MuJoCo) and making sure, everything learns properly and there are no regressions.
* We are still targeting this for the next major release (Ray 2.3).

After merging the PR, we still have to:
* Make sure users can set their custom seeds/options per individual reset() call.
* Make sure rendering works properly again.

**Comment by sven1977** [comment]
Another update:
* Release tests on the gymnasium PR are all confirmed passing.
* Merge should happen within next few days (maybe even today).

**Comment by sven1977** [comment]
This has been completed!

We will follow up very closely with remaining minor fixes:
* proper documentation on how to migrate
* enable per-episode seeding via callbacks
* rendering
* further development and enhancements on our multi-agent env API.

**Comment by maziarg** [comment]
I have beed using the nightly-build of RLlib that supports Gymnasium and training some RL models but all of a sudden I started getting this error `AttributeError: '_TFStub' object has no attribute 'Tensor' any idea how I can resolve this issue?
`

**Comment by GDiaz16** [comment]
Hello guys! I´ve been working with the latest version 2.2.0, and this error happened to me, I don´t know where I can find the nightly version to install with pip, or a version that works with gymnasium, I will be grateful if you point me in the right direction.
