### ISSUE TITLE
Error compiling Ray on some versions of macOS

### ISSUE THREAD

**Issue by pcmoritz** [ray-project/ray#1686]
```
In file included from /Users/pcmoritz/ray/src/ray/raylet/lineage_cache.cc:1:
    /Users/pcmoritz/ray/src/ray/raylet/lineage_cache.h:19:8: error: private field 'dirty_' is not used [-Werror,-Wunused-private-field]
      bool dirty_;
           ^
    1 error generated.
```

**Comment by robertnishihara** [comment]
Yeah I ran into that as well.. had to comment it out.

**Comment by pcmoritz** [comment]
PR here: https://github.com/ray-project/ray/pull/1687

**Comment by atumanov** [comment]
builds on 10.11 + the Travis Xcode7 images. Do we have a support matrix? Builds are currently not tested on 10.13.

**Comment by robertnishihara** [comment]
Same problem on 10.12.6.

**Comment by atumanov** [comment]
in that case, given such a difference in the build process, we should consider adding 10.12+ to the CI. There's no way for pre-10.12 contributors to catch such build errors otherwise...

**Comment by robertnishihara** [comment]
Looks like it was actually caught by our Jenkins Mac OS build https://amplab.cs.berkeley.edu/jenkins/job/Ray-macos/279/ (but right now that's only building the master and isn't testing the PRs I think).

**Comment by robertnishihara** [comment]
Fixed by #1687
