### ISSUE TITLE
[tune] Issues importing from tune-sklearn

### ISSUE THREAD

**Issue by mrhoody** [ray-project/ray#9711]
### What is the problem?
Hi, I have just installed the latest versions of tune sklearn but am having difficulty with importing TuneGridSearchCV. It gives me this error message: "AttributeError: type object 'sklearn.tree._criterion.array' has no attribute '__reduce_cython__'"
*Ray version and other system information (Python version, TensorFlow version, OS):*
I currently have ray version 0.8.6, scikit-optimize 0.7.4 and scikit-learn 0.23.1. I am working on windows 10 with python 3.7.3 installed via anaconda.
### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):
from tune_sklearn import TuneGridSearchCV

- [X] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

**Comment by richardliaw** [comment]
@mrhoody looks like a scikit-learn conda versioning issue - https://stackoverflow.com/questions/55605667/attributeerror-type-object-sklearn-tree-tree-treebuilder-has-no-attribute

**Comment by richardliaw** [comment]
Closing this for now - if this continues to be an issue please open an issue on tune-sklearn. Thanks!
