### PR TITLE
Revert "[Datasets] [Tensor Story - 1/2] Automatically provide tensor views to UDFs and infer tensor blocks for pure-tensor datasets."

### PR DESCRIPTION
**Pull request by krfricke**
Reverts ray-project/ray#24812

Broke e.g. ML tests: https://buildkite.com/ray-project/ray-builders-branch/builds/7667#55e7473e-f6a8-4d72-a875-cd68acf8b0c4

```


(TrainTrainable pid=3949)     self.ret = self._target(*self._args, **self._kwargs)
--


<span class="term-fg36 term-fg2">(TrainTrainable pid=3949)</span> AttributeError: 'numpy.ndarray' object has no attribute 'memory_usage'
```

### CODE REVIEW

**Review by maxpumperla — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]

**Review by jjyao — APPROVED** [review]

**Comment by clarkzinzow** [comment]
Thanks for reverting y'all, not sure why the ML tests job passed in the PR build but not in master, most likely a parallel merge? https://buildkite.com/ray-project/ray-builders-pr/builds/32806#d5b191c9-df69-4f2d-9baf-7d61f3eb15f5

**Comment by clarkzinzow** [comment]
@ericl It looks like your check ingest utility always expects the native batch type to be a Pandas DataFrame, pushing up a re-revert PR now.

**Comment by krfricke** [comment]
The test was introduced in https://github.com/ray-project/ray/commit/995309f9a3216c7b125d241d09584434d3a11c18, so if that wasn't merged into the PR, that could be the reason
