### ISSUE TITLE
[Datasets] map_batches with compute="actors" returns invalid dataset

### ISSUE THREAD

**Issue by a-ro** [ray-project/ray#23868]
### What happened + What you expected to happen

1. I had a script running `dataset.map_batches` that worked well in Ray 1.8. After upgrading to Ray 1.11, I'm unable to perform some operations with the dataset returned by `map_batches`.  This works if I use `compute="tasks"` instead. 
```
output = ds.map_batches(MyModel, batch_format="pandas", compute="actors", batch_size=2, num_cpus=1,)
print(output)
```
Error:
```
AttributeError: 'ray._raylet.ObjectRef' object has no attribute 'schema'
```
2. Expected behavior:
```
Dataset(num_blocks=1, num_rows=3, schema={one: int64, two: string})
```
3. Full stacktrace
```
Input In [30], in <cell line: 1>()
----> 1 print(output)

File /.../, in Dataset.__str__(self)
   2542 def __str__(self) -> str:
-> 2543     return repr(self)

File /../ray/data/dataset.py:2525, in Dataset.__repr__(self)
   2524 def __repr__(self) -> str:
-> 2525     schema = self.schema()
   2526     if schema is None:
   2527         schema_str = "Unknown schema"

File /.../ray/data/dataset.py:1418, in Dataset.schema(self, fetch_if_missing)
   1415 # Some blocks could be empty, in which case we cannot get their schema.
   1416 # TODO(ekl) validate schema is the same across different blocks.
   1417 for m in metadata:
-> 1418     if m.schema is not None:
   1419         return m.schema
   1420 if not fetch_if_missing:
AttributeError: 'ray._raylet.ObjectRef' object has no attribute 'schema'
```

### Versions / Dependencies

macOS Monterey 12.3.1
Python 3.9.7
pandas==1.3.5
ray==1.11.0

### Reproduction script

```python
import pandas as pd
import ray


class MyModel:
    def __init__(self):
        self.my_parameter = 3
    
    def __call__(self, batch:pd.DataFrame) -> pd.DataFrame:
        return batch

    
ray.init()
pdf = pd.DataFrame({"one": [1, 2, 3], "two": ["a", "b", "c"]})
ds = ray.data.from_pandas([pdf])
output = ds.map_batches(MyModel, batch_format="pandas", compute="actors", batch_size=2, num_cpus=1,)

# this fails
output.schema()

# this also fails
output.to_pandas()

# another fail
print(output)
```

**Comment by clarkzinzow** [comment]
@a-ro This succeeds for me on latest master when using a [nightly wheel](https://docs.ray.io/en/master/ray-overview/installation.html#daily-releases-nightlies) or one of the [soon-to-be-published 1.12 wheels](https://test.pypi.org/project/ray/1.12.0/#files). Could you try one of those wheels and confirm that it works on your end?

**Comment by clarkzinzow** [comment]
Closing this since it's fixed on latest master.

**Comment by a-ro** [comment]
Sorry for the late reply, I confirm we tested it on our side and it's fixed.

**Comment by clarkzinzow** [comment]
@a-ro No worries, thank you for confirming! 🙌
