### PR TITLE
[Datasets] Refactor iter_rows() for DatasetIterator classes

### LINKED ISSUE #33263: [Datasets] `test_streaming_split_e2e` is failing
### What happened + What you expected to happen

`test_streaming_integration` has been broken since https://github.com/ray-project/ray/commit/694a74acedb17fc3a07fb0972404a46f7660deb1. Tests passed on the PR but are failing on master, so this is possibly merge-related.

```
ray_start_10_cpus_shared = RayContext(dashboard_url='127.0.0.1:8265', python_version='3.7.9', ray_version='3.0.0.dev0', ray_commit='{{RAY_COMMIT_...3:48107', 'dashboard_agent_listen_port': 52365, 'node_id': '5bbb1fc4077cfb176948562247f805555fd503a170ab8b59dc893014'})

    def test_streaming_split_e2e(ray_start_10_cpus_shared):
        def get_lengths(*iterators):
            lengths = []
            for it in iterators:
                x = 0
                for batch in it.iter_batches():
                    x += len(batch)
                lengths.append(x)
            lengths.sort()
            return lengths
    
        ds = ray.data.range(1000)
        (
            i1,
            i2,
        ) = ds.streaming_split(2, equal=True)
>       lengths = get_lengths(i1, i2)

python/ray/data/tests/test_streaming_integration.py:107: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
python/ray/data/tests/test_streaming_integration.py:96: in get_lengths
    for batch in it.iter_batches():
/ray/python/ray/data/_internal/stream_split_dataset_iterator.py:115: in iter_batches
    shuffle_seed=local_shuffle_seed,
/ray/python/ray/data/_internal/block_batching.py:123: in batch_block_refs
    prefetch_batches=prefetch_batches,
/ray/python/ray/data/_internal/block_batching.py:172: in batch_blocks
    for formatted_batch in batch_iter:
/ray/python/ray/data/_internal/block_batching.py:398: in _format_batches
    for block in block_iter:
/ray/python/ray/data/_internal/block_batching.py:361: in _blocks_to_batches
    for block in block_iter:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

block_ref_iter = <generator object _prefetch_blocks at 0x7f9b303c2750>
stats = None

    def _resolve_blocks(
        block_ref_iter: Iterator[ObjectRef[Block]],
        stats: Optional[Union[DatasetStats, DatasetPipelineStats]] = None,
    ) -> Iterator[Block]:
        """Given an iterator of unresolved blocks (as Ray object references), returns an
        iterator of resolved blocks.
    
        The length of the returned iterator may be less than the length of the original
        if any of the references in the original iterator are None.
    
        Args:
            block_ref_iter: An iterator over block object references.
            stats: Dataset stats object used to store block fetching time.
    
        Returns:
            An iterator over resolved blocks.
        """
    
        hit = 0
        miss = 0
        unknown = 0
        for block_ref in block_ref_iter:
            if block_ref is not None:
                stats_timer = stats.iter_get_s.timer() if stats else nullcontext()
                # Count the number of blocks that we hit locally or miss (so have to
                # fetch from remote node). This is to measure the effectiveness of
                # prefetch.
                loc = ray.experimental.get_object_locations([block_ref])
                nodes = loc[block_ref]["node_ids"]
                if nodes:
                    current = ray.get_runtime_context().get_node_id()
                    if current in nodes:
                        hit += 1
                    else:
                        miss += 1
                else:
                    unknown += 1
                with stats_timer:
                    block = ray.get(block_ref)
                yield block
>       stats.iter_blocks_local = hit
E       AttributeError: 'NoneType' object has no attribute 'iter_blocks_local'

/ray/python/ray/data/_internal/block_batching.py:265: AttributeError
```

### Versions / Dependencies

Master

### Reproduction script

See above.

### Issue Severity

None

### PR DESCRIPTION
**Pull request by c21**
## Why are these changes needed?

This is to fix CI test failure introduced in https://github.com/ray-project/ray/pull/33180 ([example of buildkite failure](https://buildkite.com/ray-project/oss-ci-build-branch/builds/2690#0186da0a-17c7-40dd-a43c-1de36c4894f4)). We need to add `iter_rows()` method for StreamSplitDatasetIterator as well.

Screen Shot 2023-03-13 at 11 24 05 AM

## Related issue number

Closes #33263 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: python/ray/data/_internal/stream_split_dataset_iterator.py [hunk 1]
```diff
@@ -115,6 +117,18 @@ def gen_blocks() -> Iterator[ObjectRef[Block]]:
             shuffle_seed=local_shuffle_seed,
         )
 
+    def iter_rows(self, *, prefetch_blocks: int = 0) -> Iterator[Union[T, TableRow]]:
+        # During row-based ops, we also choose a batch format that lines up with the
+        # current dataset format in order to eliminate unnecessary copies and type
+        # conversions.
+        batch_format = _get_batch_format(self._base_dataset)
+        for batch in self.iter_batches(
```
Comment (ericl) [inline python/ray/data/_internal/stream_split_dataset_iterator.py:125]: This is basically the same as the other impl. Could we make this not an abstract method, and delete the impl in this file?

Comment (ericl) [reply python/ray/data/_internal/stream_split_dataset_iterator.py:125]: (move the common impl to dataset_iterator.py, and then delete the methods in stream_split_dataset_iterator.py and dataset_iterator_impl.py)

Comment (c21) [reply python/ray/data/_internal/stream_split_dataset_iterator.py:125]: Ok, I put it in this way because `PipelinedDatasetIterator.iter_rows` has its own impl. So technically these 3 subclasses not sharing same `iter_rows` impl. But I can put it inside `DatasetIterator.iter_rows`.

Comment (ericl) [reply python/ray/data/_internal/stream_split_dataset_iterator.py:125]: I think that one can also use the same impl...

Comment (ericl) [reply python/ray/data/_internal/stream_split_dataset_iterator.py:125]: (We could make get_batch_format() an abstract method instead, like schema)

Comment (c21) [reply python/ray/data/_internal/stream_split_dataset_iterator.py:125]: Actually I found [`PipelinedDatasetIterator.iter_batches()` iterate next dataset internally](https://github.com/ray-project/ray/blob/master/python/ray/data/_internal/pipelined_dataset_iterator.py#L42), I don't want to further complicate `PipelinedDatasetIterator.iter_batches` interface. How about we leave the implenmentation as it is for now?

Comment (ericl) [reply python/ray/data/_internal/stream_split_dataset_iterator.py:125]: To be clear, this is my proposal, and I believe we can remove most of the other code after this.

```
class DatasetIterator:
 def iter_rows(...):
   target_format = self._best_batch_format()
   for batch in self.iter_batches(target_format):
        ...
           yield row
           
 def _best_batch_format():
    return "default"   # can override to customize in DatasetIteratorImpl
```

Comment (c21) [reply python/ray/data/_internal/stream_split_dataset_iterator.py]: @ericl - ah got it. Updated.

File: python/ray/data/dataset_iterator.py [hunk 2]
```diff
@@ -700,3 +704,11 @@ def _is_tensor_dataset(self) -> bool:
         if schema is None or isinstance(schema, type):
             return False
         return _is_tensor_schema(schema.names)
+
+    def _best_batch_format(self) -> Literal["default", "pandas", "pyarrow", "numpy"]:
+        """Returns the best batch format that lines up with the dataset format.
```
Comment (jianoaix) [inline python/ray/data/dataset_iterator.py:709]: What does it mean "best"? Matching the dataset format doesn't necessarily has the best perf, e.g. pyarrow-to-pandas conversion can be faster than pandas-to-pandas conversion.

File: python/ray/data/_internal/util.py [hunk 3]
```diff
@@ -397,3 +404,28 @@ def _split_list(arr: List[Any], num_splits: int) -> List[List[Any]]:
         arr[i * q + min(i, r) : (i + 1) * q + min(i + 1, r)] for i in range(num_splits)
     ]
     return splits
+
+
+def _best_batch_format(
```
Comment (jianoaix) [inline python/ray/data/_internal/util.py:409]: If this can be a util, why cannot it be the default impl for `DatasetIterator`?

Comment (c21) [reply python/ray/data/_internal/util.py:409]: So `DatasetIterator` has no definition of `ds: "Dataset`. `PipelinedDatasetIterator` just uses `base_dataset_pipeline`. And `DatasetIteratorImpl` and `StreamSplitDatasetIterator` uses `_base_dataset`.

File: python/ray/data/dataset_iterator.py (hunk 2 above)
Comment (c21) [reply python/ray/data/dataset_iterator.py:709]: @jianoaix - I am open to a better name, do you have a suggestion for naming?

Comment (jianoaix) [reply python/ray/data/dataset_iterator.py:709]: `_default_batch_format` to align with Dataset (the idea of "best" can be in comment)?
Also since here is a best determined batch format, should it also be used by `iter_batches` when the batch_format arg is not specified by users?

Comment (c21) [reply python/ray/data/dataset_iterator.py:709]: I guess I won't touch the batch format behavior for `iter_batches`, that would trigger more change and dsicussion across `Dataset` and `DatasetIterator`. ideally I want this PR should be simple one to unblock CI test failure. I can do the renaming part.

**Review by ericl — APPROVED** [review]

File: python/ray/data/dataset_iterator.py (hunk 2 above)
Comment (jianoaix) [reply python/ray/data/dataset_iterator.py:709]: It should be simple but this invites a question why do we have a class member which determines the best format in the context of iterator, but is not actually used for iter_batches().

Comment (c21) [reply python/ray/data/dataset_iterator.py:709]: The current behavior for `iter_batches` is always using the "default" if user does not provide. The `iter_rows` behavior is different - in bulk execution, it checks `Dataset.dataset_format()` and uses the returned one, while in streaming execution, it uses "default".

The difference is already happening before this PR, and here we just introduce a private method in `DatasetIterator`, so it should be easy to change/remove later. Can we defer the behavior change for `iter_batches` to a future PR?

Comment (jianoaix) [reply python/ray/data/dataset_iterator.py:709]: Yeah, SG

**Review by jianoaix — APPROVED** [review]
