### ISSUE TITLE
[Dashboard] ImportError: cannot import name dataclass_transform in init pydantic.dataclasses

### ISSUE THREAD

**Issue by YQ-Wang** [ray-project/ray#31227]
### What happened + What you expected to happen

I use the rayproject/ray-ml:2.2.0-cpu (head) and rayproject/ray-ml:2.2.0-gpu (worker) as the base images to build the custom Ray images in the K8S cluster. But I got the following error message when trying to port forwarding to the Ray Cluster.
```
E1219 19:21:18.432446    1303 portforward.go:400] an error occurred forwarding 8265 -> 8265: error forwarding port 8265 to pod 9b23ce9b139c60ce4bcdc5352da627e9caeff7a99bdfc2d6ea56288b43f4509a, uid : exit status 1: 2022/12/20 03:21:18 socat[23027] E connect(5, AF=2 127.0.0.1:8265, 16): Connection refused
```

dashboard.log has the following error message:
```
2022-12-19 17:02:38,214 INFO head.py:128 -- Dashboard head grpc address: 0.0.0.0:37563
2022-12-19 17:02:38,222 INFO head.py:234 -- Starting dashboard metrics server on port 44227
2022-12-19 17:02:38,229 INFO utils.py:112 -- Get all modules by type: DashboardHeadModule
2022-12-19 17:02:38,422 ERROR dashboard.py:230 -- The dashboard on node deployment-ray-head-74668d6f99-dbqs2 failed with the following error:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 219, in <module>
    loop.run_until_complete(dashboard.run())
  File "/home/ray/anaconda3/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 66, in run
    await self.dashboard_head.run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/head.py", line 290, in run
    modules = self._load_modules(self._modules_to_load)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/head.py", line 197, in _load_modules
    head_cls_list = dashboard_utils.get_all_modules(DashboardHeadModule)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/utils.py", line 121, in get_all_modules
    importlib.import_module(name)
  File "/home/ray/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/modules/actor/actor_head.py", line 11, in <module>
    import ray.dashboard.optional_utils as dashboard_optional_utils
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/optional_utils.py", line 26, in <module>
    from ray.dashboard.optional_deps import PathLike, RouteDef, aiohttp, hdrs
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/dashboard/optional_deps.py", line 18, in <module>
    import pydantic  # noqa: F401
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 52, in init pydantic.dataclasses
ImportError: cannot import name dataclass_transform
```

### Versions / Dependencies

rayproject/ray-ml:2.2.0-cpu (head) and rayproject/ray-ml:2.2.0-gpu (worker)
Python: 3.7
ENV: K8S

### Reproduction script

no reproduction script, just the official base images.

### Issue Severity

High: It blocks me from completing my task.

**Comment by YQ-Wang** [comment]
I can confirm that this issue has been resolved after upgrading typing_extensions to 4.4.0. Thanks @architkulkarni !

**Comment by 0x2b3bfa0** [comment]
`ray exec cluster.yaml 'pip install typing_extensions==4.4.0' && ray exec 'ray start'` works for me
