### ISSUE TITLE
[Tune] PBT Transformers example not working with Transformers v3.0.2 and v4.0.0

### ISSUE THREAD

**Issue by rsuwaileh** [ray-project/ray#12641]
I'm trying to run the pbt_transformers example from Ray examples: https://docs.ray.io/en/latest/tune/examples/pbt_transformers.html#pbt-transformers-example

I was using Transformers v3.0.2, but I got a `no such argument error` for the `model_init` argument or `Trainer`!

If I changed `model_init` to `model`, I get the following error:

```
Traceback (most recent call last):
  File "pbt_trans.py", line 168, in <module>
    tune_transformer(
  File "pbt_trans.py", line 87, in tune_transformer
    trainer = Trainer(
  File "/home/.../lib/python3.8/site-packages/transformers/trainer.py", line 244, in __init__
    self.model = model.to(args.device) if model is not None else None
AttributeError: 'function' object has no attribute 'to'
```

After checking the Transformers Trainer source code I found `model_init` exists only in Transformers v4.0.0 so I installed it and I had to remove the `evaluate_during_training` argument from `TrainingArguments(...)` to make the code compatible with Transformers v4.0.0!

Now, I'm getting this error:

```
Traceback (most recent call last):
  File "pbt_trans.py", line 168, in <module>
    tune_transformer(
  File "pbt_trans.py", line 105, in tune_transformer
    scheduler = PopulationBasedTraining(
  File "/home/.../lib/python3.8/site-packages/ray/tune/schedulers/pbt.py", line 188, in __init__
    raise TypeError("`hyperparam_mutation` values must be either "
TypeError: `hyperparam_mutation` values must be either a List, Dict, or callable.
```

pbt_trans.py is an exact copy of the example on the page above with the changes I mentioned above!

- Any hints to resolve this error?
- What version of Transformers I should use to run this example?

**Comment by amogkam** [comment]
Hi @rsuwaileh, what version of Ray are you using? Can you upgrade to Ray v1.0.1 and try again.

Regarding the transformers version, this should work on >v3.1, but we haven't tested on 4.0 yet (which just got released a few days ago). It seems like you already found some changes that need to be made for this example to work on 4.0. If you plan to us 4.0, it would be great if you could make a PR with the changes you had to make to get this working!

Hope this helps!

**Comment by rsuwaileh** [comment]
Hi @amogkam I was using 0.8.7.
Using transformers-3.5.1 seemed to solve the errors above, but it appears in the logging that one trial Running, but when I check `nvidia-smi`, I see no processes running!

So, I installed ray-1.0.1 as you suggested (with transformers-3.5.1), but I'm getting a new error:
```
Traceback (most recent call last):
  File "/home/.../lib/python3.8/site-packages/ray/tune/suggest/variant_generator.py", line 199, in _resolve_domain_vars
    value = domain.sample(_UnresolvedAccessGuard(spec))
  File "/home/.../lib/python3.8/site-packages/ray/tune/sample.py", line 48, in sample
    return sampler.sample(self, spec=spec, size=size)
  File "/home/.../lib/python3.8/site-packages/ray/tune/sample.py", line 276, in sample
    items = [
  File "/home/.../lib/python3.8/site-packages/ray/tune/sample.py", line 277, in <listcomp>
    domain.func(spec[i] if isinstance(spec, list) else spec)
  File "pbt_transformers.py", line 97, in <lambda>
    lambda spec: len(train_dataset) // spec.config["per_device_train_batch_size"] + 1  # noqa: E501
KeyError: 'per_device_train_batch_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pbt_transformers.py", line 167, in <module>
    tune_transformer(
  File "pbt_transformers.py", line 126, in tune_transformer
    trainer.hyperparameter_search(
  File "/home/.../lib/python3.8/site-packages/transformers/trainer.py", line 1038, in hyperparameter_search
    best_run = run_hp_search(self, n_trials, direction, **kwargs)
  File "/home/.../lib/python3.8/site-packages/transformers/integrations.py", line 225, in run_hp_search_ray
    analysis = ray.tune.run(_objective, config=trainer.hp_space(None), num_samples=n_trials, **kwargs)
  File "/home/.../lib/python3.8/site-packages/ray/tune/tune.py", line 411, in run
    runner.step()
  File "/home/.../lib/python3.8/site-packages/ray/tune/trial_runner.py", line 561, in step
    next_trial = self._get_next_trial()  # blocking
  File "/home/.../lib/python3.8/site-packages/ray/tune/trial_runner.py", line 658, in _get_next_trial
    self._update_trial_queue(blocking=wait_for_trial)
  File "/home/.../lib/python3.8/site-packages/ray/tune/trial_runner.py", line 1011, in _update_trial_queue
    trial = self._search_alg.next_trial()
  File "/home/.../lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 91, in next_trial
    return next(self._trial_iter)
  File "/home/.../lib/python3.8/site-packages/ray/tune/suggest/basic_variant.py", line 113, in _generate_trials
    for resolved_vars, spec in generate_variants(unresolved_spec):
  File "/home/.../lib/python3.8/site-packages/ray/tune/suggest/variant_generator.py", line 46, in generate_variants
    for resolved_vars, spec in _generate_variants(unresolved_spec):
  File "/home/.../lib/python3.8/site-packages/ray/tune/suggest/variant_generator.py", line 160, in _generate_variants
    resolved_vars = _resolve_domain_vars(resolved_spec, domain_vars)
  File "/home/.../lib/python3.8/site-packages/ray/tune/suggest/variant_generator.py", line 203, in _resolve_domain_vars
    raise ValueError(
ValueError: Failed to evaluate expression: ('config', 'eval_steps'): <ray.tune.sample.Function object at 0x7f5c6bb7dc70>

```

**Comment by amogkam** [comment]
@rsuwaileh Ah sorry that looks like a bug on our end. Can you add “per_device_train_batch_size” to the tune_config dict and set it to whatever value you’d like (16, 32, etc.). This should fix the KeyError you are seeing. And then if that is able to run but you still don’t see any GPU usage, can you post some screenshots of the stdout and I can help out further.

**Comment by amogkam** [comment]
@rsuwaileh the `ValueError` that you are seeing should be fixed in the latest master https://github.com/ray-project/ray/pull/13174. 

I'm going to close this issue for now, but if you are still seeing problems with GPU not being utilized, feel free to reopen this and I can take a look! Thanks.
