### PR TITLE
[Windows] Fix windows build

### PR DESCRIPTION
**Pull request by ijrsvt**
The windows build has been broken since #12341 
The error is [here](https://github.com/ray-project/ray/runs/1482605583#step:7:630) and is basically the following for the `src/ray/raylet/test/local_object_manager_test.cc`:
```
error C2338: The C++ Standard forbids containers of const elements because allocator<const T> is ill-formed.
note: see reference to class template instantiation 'std::_Default_allocator_traits<_Alloc>' being compiled
        with
        [
            _Alloc=std::allocator<const ray::rpc::DeleteSpilledObjectsRequest>
        ]
```

NOTE: This is _separate_ from the Serve test failure :'( 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ffbin — APPROVED** [review]
LGTM
