### ISSUE TITLE
[Serve][LLM] Changes in `make_fastapi_ingress` between Ray 2.54 and Ray 2.55 breaks extensibility

### ISSUE THREAD

**Issue by Dekermanjian** [ray-project/ray#63170]
### What happened + What you expected to happen

Ray 2.55.1 would be backwards compatible with the way `make_fastapi_ingress` works. 

### Versions / Dependencies

The issue is specific to Ray 2.55.1

### Reproduction script

I used to be able to run the following extended ingress.

```
import os

import ray
from ray import serve
from ray.serve.llm import LLMConfig
from ray.serve.llm.deployment import LLMServer
from ray.serve.llm.ingress import OpenAiIngress, make_fastapi_ingress
from ray.llm._internal.serve.observability.logging import get_logger

from fastapi import Request
import httpx
import json

logger = get_logger("ray.serve")

# Model configuration

llm_config_m1 = LLMConfig(
    model_loading_config={
        "model_id": "qwen3-coder",
        "model_source": "Qwen/Qwen2.5-0.5B-Instruct",
    },
    engine_kwargs={
        "dtype": "bfloat16",
        "gpu_memory_utilization": 0.9,
        "trust_remote_code": True,
        "tensor_parallel_size": 1,
        "enable_auto_tool_choice": True,
        "tool_call_parser": "qwen3_coder",
    },
    deployment_config={
        "autoscaling_config": {
            "min_replicas": 1,
            "max_replicas": 1,
        },
    },
    log_engine_metrics=True,
)

llm_configs = [llm_config_m1]

deployments = []

for cfg in llm_configs:
    server_options = LLMServer.get_deployment_options(cfg)

    deployment = (
        serve.deployment(LLMServer)
        .options(
            name=f"LLMServer:{cfg.model_loading_config.model_id}", **server_options
        )
        .bind(cfg)
    )

    deployments.append(deployment)

ingress_options = OpenAiIngress.get_deployment_options(llm_configs=llm_configs)

BaseIngress = make_fastapi_ingress(OpenAiIngress)


class ExtendedIngress(BaseIngress):
    """
    Extended Ingress that adds Anthropic /v1/messages endpoint
    """

    def __init__(self, *args, **kwargs):
        """Init BaseIngress"""
        super().__init__(*args, **kwargs)

        app = self.app

        @app.post("/v1/messages")
        async def anthropic_messages(req: Request):
            """anthropic message adapter layer"""
            body = await req.json()

            openai_tools = []
            for tool in body.get("tools", []):
                openai_tools.append(
                    {
                        "type": "function",
                        "function": {
                            "name": tool["name"],
                            "description": tool.get("description", ""),
                            "parameters": tool.get("input_schema", {}),
                        },
                    }
                )

            openai_messages = []
            for m in body.get("messages", []):
                role = m["role"]
                content = m["content"]

                if isinstance(content, str):
                    openai_messages.append({"role": role, "content": content})
                elif isinstance(content, list):
                    text_buffer = ""
                    tool_calls = []
                    for block in content:
                        if block["type"] == "text":
                            text_buffer += block["text"]
                        elif block["type"] == "tool_use":
                            tool_calls.append(
                                {
                                    "id": block["id"],
                                    "type": "function",
                                    "function": {
                                        "name": block["name"],
                                        "arguments": json.dumps(block["input"]),
                                    },
                                }
                            )
                        elif block["type"] == "tool_result":
                            openai_messages.append(
                                {
                                    "role": "tool",
                                    "tool_call_id": block["tool_use_id"],
                                    "content": str(block.get("content", "")),
                                }
                            )

                    if role == "assistant":
                        msg_obj = {
                            "role": "assistant",
                            "content": text_buffer if text_buffer else None,
                        }
                        if tool_calls:
                            msg_obj["tool_calls"] = tool_calls
                        openai_messages.append(msg_obj)

                    elif role == "user" and text_buffer:
                        openai_messages.append({"role": "user", "content": text_buffer})

            openai_payload = {
                "model": body["model"],
                "messages": openai_messages,
                "max_tokens": body.get("max_tokens"),
                "temperature": body.get("temperature", 0.7),
            }
            if openai_tools:
                openai_payload["tools"] = openai_tools

            async with httpx.AsyncClient() as client:
                r = await client.post(
                    "http://localhost:8000/v1/chat/completions",
                    json=openai_payload,
                    timeout=30,
                )

            raw_text = r.text
            status = r.status_code

            try:
                resp = r.json()
            except Exception:
                return {
                    "error": "Invalid JSON from upstream",
                    "status_code": status,
                    "raw": raw_text,
                }

            if status != 200:
                return {
                    "error": "Upstream request failed",
                    "status_code": status,
                    "body": resp,
                }

            if "error" in resp:
                return {"error": resp["error"]}

            choices = resp.get("choices")

            if not choices:
                return {
                    "error": "No choices returned from upstream",
                    "full_response": resp,
                }

            msg = choices[0].get("message", {})
            tool_calls = msg.get("tool_calls") or []
            content_blocks = []

            if msg.get("content"):
                content_blocks.append({"type": "text", "text": msg["content"]})

            for tc in tool_calls:
                fn = tc.get("function", {})
                try:
                    args = json.loads(fn.get("arguments") or "{}")
                except Exception:
                    args = {}
                content_blocks.append(
                    {
                        "type": "tool_use",
                        "id": tc.get("id"),
                        "name": fn.get("name"),
                        "input": args,
                    }
                )

            usage = resp.get("usage", {})

            anthropic_usage = {
                "input_tokens": usage.get("prompt_tokens", 0),
                "output_tokens": usage.get("completion_tokens", 0),
            }

            return {
                "id": resp.get("id", "msg_qwen"),
                "type": "message",
                "role": "assistant",
                "model": body["model"],
                "content": content_blocks,
                "stop_reason": "tool_use" if tool_calls else "end_turn",
                "usage": anthropic_usage,
            }


ingress_deployment = (
    serve.deployment(ExtendedIngress).options(**ingress_options).bind(deployments)
)

# Run the app
serve.run(ingress_deployment, name="openai-llm", route_prefix="/", blocking=True)
```

But with 2.55.1 I get:

```
AttributeError: 'ExtendedIngress' object has no attribute '_serve_asgi_lifespan'
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by ps2181** [comment]
HIi @Dekermanjian  I think it's a regression introduced by #61490, which changed `ASGIIngressWrapper.__init__` from `def` to `async def` to fix a different bug (async user constructors being silently dropped). Unfortunately, that fix introduced the same class of bug one level up: now any **subclass** with a sync `__init__` that calls `super().__init__(...)` silently drops the parent coroutine, leaving `_serve_asgi_lifespan` (and the rest of `ASGIAppReplicaWrapper.__init__`) unrun — hence the `AttributeError` you see at startup.

### Workaround (works today on 2.55.x)

Change your `ExtendedIngress` to use an async constructor:

```python
class ExtendedIngress(make_fastapi_ingress(OpenAiIngress)):
    async def __init__(self, *args, **kwargs):
        await super().__init__(*args, **kwargs)
        # ... your custom setup

**Comment by Dekermanjian** [comment]
Thank you @ps2181. This work around helped me circumvent the issue.

**Comment by ps2181** [comment]
> Thank you [@ps2181](https://github.com/ps2181). This work around helped me circumvent the issue.

Glad that helped!
