### ISSUE TITLE
Cannot register custom serializers before ray.init().

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#2524]
```python
import ray

class Foo:
    pass

def s(obj):
    return obj

def d(obj):
    return obj

ray.register_custom_serializer(Foo, serializer=s, deserializer=d)
```

Fails with

```
AttributeError                            Traceback (most recent call last)
<ipython-input-5-ab10f55b546d> in <module>()
----> 1 ray.register_custom_serializer(Foo, serializer=s, deserializer=d)

~/Workspace/ray/python/ray/worker.py in register_custom_serializer(cls, use_pickle, use_dict, serializer, deserializer, local, driver_id, class_id, worker)
   2421 
   2422     if driver_id is None:
-> 2423         driver_id_bytes = worker.task_driver_id.id()
   2424     else:
   2425         driver_id_bytes = driver_id.id()

AttributeError: 'NoneType' object has no attribute 'id'
```

Probably introduced in https://github.com/ray-project/ray/pull/2406.

It should be possible to define custom serializers before `ray.init()` (e.g., in other Python modules). The solution is probably to allow the driver ID to be `None` when `register_custom_serializer` is cached and then pass in the driver ID when it actually gets run when `ray.init()` is called.

**Comment by robertnishihara** [comment]
On a separate note, we may want to move more toward using built in things like `__getstate__`/`__setstate__`.

**Comment by ericl** [comment]
Auto-closing stale issue.
