### PR TITLE
Make Ray compile on Python 3.12

### LINKED ISSUE #45477: [Core] upgrade to python 3.12
### Description

https://github.com/ray-project/ray/pull/45019 is the initial effort to upgrade ray to python 3.12. I'm hitting with this compilation error that will need core's support https://buildkite.com/ray-project/premerge/builds/25129#018f27f7-9904-4d29-95e2-0c8e9da4a752/177-678

```
[2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp: In function 'PyObject* __pyx_f_3ray_7_raylet_increase_recursion_limit()':
--
  | [2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp:942:37: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'recursion_limit'; did you mean 'py_recursion_limit'?
  | [2024-04-29T03:54:49Z]   942 \|     #define CURRENT_DEPTH(x)  ((x)->recursion_limit - (x)->recursion_remaining)
  | [2024-04-29T03:54:49Z]       \|                                     ^~~~~~~~~~~~~~~
  | [2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp:942:37: note: in definition of macro 'CURRENT_DEPTH'
  | [2024-04-29T03:54:49Z]   942 \|     #define CURRENT_DEPTH(x)  ((x)->recursion_limit - (x)->recursion_remaining)
  | [2024-04-29T03:54:49Z]       \|                                     ^~~~~~~~~~~~~~~
  | [2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp:942:60: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'recursion_remaining'; did you mean 'c_recursion_remaining'?
  | [2024-04-29T03:54:49Z]   942 \|     #define CURRENT_DEPTH(x)  ((x)->recursion_limit - (x)->recursion_remaining)
  | [2024-04-29T03:54:49Z]       \|                                                            ^~~~~~~~~~~~~~~~~~~
  | [2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp:942:60: note: in definition of macro 'CURRENT_DEPTH'
  | [2024-04-29T03:54:49Z]   942 \|     #define CURRENT_DEPTH(x)  ((x)->recursion_limit - (x)->recursion_remaining)
  | [2024-04-29T03:54:49Z]       \|                                                            ^~~~~~~~~~~~~~~~~~~
  | [2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp: In function 'void __Pyx_Raise(PyObject*, PyObject*, PyObject*, PyObject*)':
  | [2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp:144254:36: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'curexc_traceback'
  | [2024-04-29T03:54:49Z] 144254 \|         PyObject* tmp_tb = tstate->curexc_traceback;
  | [2024-04-29T03:54:49Z]        \|                                    ^~~~~~~~~~~~~~~~
  | [2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp:144257:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'curexc_traceback'
  | [2024-04-29T03:54:49Z] 144257 \|             tstate->curexc_traceback = tb;
  | [2024-04-29T03:54:49Z]        \|                     ^~~~~~~~~~~~~~~~
  | [2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp: In function 'PyObject* __Pyx_PyUnicode_Join(PyObject*, Py_ssize_t, Py_ssize_t, Py_UCS4)':
  | [2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp:571:51: error: '_PyUnicode_Ready' was not declared in this scope; did you mean '_PyUnicode_Copy'?
  | [2024-04-29T03:54:49Z]   571 \|                                               0 : _PyUnicode_Ready((PyObject *)(op)))
  | [2024-04-29T03:54:49Z]       \|                                                   ^~~~~~~~~~~~~~~~
  | [2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp:1136:43: note: in definition of macro 'unlikely'
  | [2024-04-29T03:54:49Z]  1136 \|   #define unlikely(x) __builtin_expect(!!(x), 0)
  | [2024-04-29T03:54:49Z]       \|                                           ^
  | [2024-04-29T03:54:49Z] bazel-out/k8-opt/bin/python/ray/_raylet.cpp:144661:22: note: in expansion of macro '__Pyx_PyUnicode_READY'
  | [2024-04-29T03:54:49Z] 144661 \|         if (unlikely(__Pyx_PyUnicode_READY(uval)))


```

### Use case

python 3.12

### PR DESCRIPTION
**Pull request by pcmoritz**
## Why are these changes needed?

Fixes https://github.com/ray-project/ray/issues/45477

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by can-anyscale — APPROVED** [review]

**Review by edoakes — APPROVED** [review]

File: python/ray/_raylet.pyx [hunk 1]
```diff
@@ -673,7 +673,9 @@ cdef increase_recursion_limit():
         int new_limit = current_limit * 2
         cdef extern from *:
             """
-#if PY_VERSION_HEX >= 0x30B00A4
+#if PY_VERSION_HEX >= 0x30C0000
+    #define CURRENT_DEPTH(x) ((x)->py_recursion_limit - (x)->py_recursion_remaining)
```
[the remark this answers is not in the document]
Comment (pcmoritz) [reply python/ray/_raylet.pyx:677]: I don't think so -- this is an internal symbol so in general there is no guarantee that it is stable. I got the change from https://github.com/python/cpython/pull/96510/files#diff-c22186367cbe20233e843261998dc027ae5f1f8c0d2e778abfa454ae74cc59deR260 :)
