### ISSUE TITLE
[dashboard] blank dashboard on RHEL7 Machine

### ISSUE THREAD

**Issue by ilonadem** [ray-project/ray#9918]
### I am working on a RHEL7.1 server and my ray dashboard is blank. The machine view section says "loading..." and "TypeError: Object entries is not a function". Logical view also says "loading...", memory says "No Memory Table Information Provided" and Ray Config tab says "No Ray configuration detected"

*Ray 0.8.6, python 3.7.0, RHEL7.1:*

## I have been running:
``` ray start --head``` 
### and then opening the dashboard on Firefox through the localhost URL outputted by ray

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).
![MicrosoftTeams-image](https://user-images.githubusercontent.com/69218138/89546999-36761100-d7d3-11ea-9516-244fba0013e4.png)

**Comment by ilonadem** [comment]
When I do "ray stack" I get: "Error: Failed to find python version from target process"

**Comment by mfitton** [comment]
@ilonadem can you try running `pip install ray[dashboard]` for me and see if that fixes your issues? Otherwise there's a file at `/tmp/ray/session_latest/logs/dashboard.err` that might have something in it. Could you attach that if so please?

**Comment by ilonadem** [comment]
@mfitton I already have ray dashboard installed, but here is the dashboard.err file:

``` I0805 23:32:11.378923 40740 40740 global_state_accessor.cc:25] Redis server address = 172.23.49.92:49270, is test flag = 0
I0805 23:32:11.379835 40740 40740 redis_client.cc:141] RedisClient connected.
I0805 23:32:11.388046 40740 40740 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0805 23:32:11.389539 40740 40740 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
Traceback (most recent call last):
  File "/home/paragc/paragc_env/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 974, in <module>
    raise e
  File "/home/paragc/paragc_env/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 961, in <module>
    dashboard.run()
  File "/home/paragc/paragc_env/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 572, in run
    self.log_dashboard_url()
  File "/home/paragc/paragc_env/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 567, in log_dashboard_url
    with open(os.path.join(self.temp_dir, "dashboard_url"), "w") as f:
PermissionError: [Errno 13] Permission denied: '/tmp/ray/dashboard_url' ```

**Comment by mfitton** [comment]
Thank you, that's very helpful. It seems like there's a permissions issue with the dashboard and the /tmp/ray directory. If you make the /tmp/ray directory writable by doing `chmod 755 /tmp/ray/` (or something to that effect I don't have a Linux box in front of me to validate the command), does that fix your issue?

**Comment by ilonadem** [comment]
@mfitton Looks like that fixed the issue. Now I just get the following warnings, and the dashboard stays blank still:
``` UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0806 15:00:32.377287 91046 91046 global_state_accessor.cc:25] Redis server address = 172.23.49.92:6379, is test flag = 0
I0806 15:00:32.378471 91046 91046 redis_client.cc:141] RedisClient connected.
I0806 15:00:32.386664 91046 91046 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0806 15:00:32.388360 91046 91046 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
2020-08-06 15:00:32,409 INFO node_stats.py:179 -- NodeStats: subscribed to RAY_REPORTER.*
2020-08-06 15:00:32,409 INFO node_stats.py:183 -- NodeStats: subscribed to RAY_LOG_CHANNEL
2020-08-06 15:00:32,409 INFO node_stats.py:187 -- NodeStats: subscribed to 9
2020-08-06 15:00:32,411 INFO node_stats.py:191 -- NodeStats: subscribed to b'ACTOR:*'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/grid/common/pkgs/python/v3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/demler/PSPICE_HUB/.virtualenv/lib/python3.7/site-packages/ray/dashboard/node_stats.py", line 208, in run
    for x in p.listen():
  File "/home/demler/PSPICE_HUB/.virtualenv/lib/python3.7/site-packages/redis/client.py", line 3553, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "/home/demler/PSPICE_HUB/.virtualenv/lib/python3.7/site-packages/redis/client.py", line 3453, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/home/demler/PSPICE_HUB/.virtualenv/lib/python3.7/site-packages/redis/client.py", line 3427, in _execute
    return command(*args, **kwargs)
  File "/home/demler/PSPICE_HUB/.virtualenv/lib/python3.7/site-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()

**Comment by ilonadem** [comment]
@mfitton I am still unable to get the ray dashboard up, and now when I try to run 
``` ray stop ```
I get the following error:
```2020-08-13 12:27:11,838	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40742, name='raylet')
2020-08-13 12:27:11,838	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40741, name='plasma_store_server')
2020-08-13 12:27:11,839	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40733, name='gcs_server')
2020-08-13 12:27:11,877	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40734, name='/home/paragc/pa')
2020-08-13 12:27:11,877	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40744, name='/home/paragc/pa')
2020-08-13 12:27:11,908	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40724, name='redis-server')
2020-08-13 12:27:11,908	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40729, name='redis-server')
2020-08-13 12:27:11,935	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40742, name='raylet')
2020-08-13 12:27:11,935	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40773, name='ray::IDLE')
2020-08-13 12:27:11,935	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40774, name='ray::IDLE')
2020-08-13 12:27:11,935	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40775, name='ray::IDLE')
2020-08-13 12:27:11,936	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40776, name='ray::IDLE')
2020-08-13 12:27:11,936	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40777, name='ray::IDLE')
2020-08-13 12:27:11,936	ERROR scripts.py:571 -- Error: psutil.AccessDenied (pid=40778, name='ray::IDLE')```

**Comment by ilonadem** [comment]
The dashboard.err file now looks like:
``` UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0812 10:26:25.090920 178127 178127 global_state_accessor.cc:25] Redis server address = 172.23.49.92:6379, is test flag = 0
I0812 10:26:25.092262 178127 178127 redis_client.cc:141] RedisClient connected.
I0812 10:26:25.100600 178127 178127 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0812 10:26:25.102015 178127 178127 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
2020-08-12 10:26:25,126 INFO node_stats.py:179 -- NodeStats: subscribed to RAY_REPORTER.*
2020-08-12 10:26:25,127 INFO node_stats.py:183 -- NodeStats: subscribed to RAY_LOG_CHANNEL
2020-08-12 10:26:25,127 INFO node_stats.py:187 -- NodeStats: subscribed to 9
2020-08-12 10:26:25,128 INFO node_stats.py:191 -- NodeStats: subscribed to b'ACTOR:*'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/grid/common/pkgs/python/v3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "<redacted path>/.virtualenv/lib/python3.7/site-packages/ray/dashboard/node_stats.py", line 208, in run
    for x in p.listen():
  File "<redacted path>/.virtualenv/lib/python3.7/site-packages/redis/client.py", line 3553, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "<redacted path>/.virtualenv/lib/python3.7/site-packages/redis/client.py", line 3453, in parse_response
    response = self._execute(conn, conn.read_response)
  File "<redacted path>/.virtualenv/lib/python3.7/site-packages/redis/client.py", line 3427, in _execute

**Comment by mfitton** [comment]
@ilonadem are you running Ray in an environment where you can run it with root permissions? I believe that would solve these errors, but I understand why you might be hesitant to do that.
Also, is there anything else to that exception at the bottom? The line it refers to in our source is a line that begins listening for messages on Redis

**Comment by mfitton** [comment]
It seems like all of these issues could be inter-process communication issues. psutil failing could also be related to the user running Ray's privileges on the machine.

Could you try running the psutil command manually from the user that you normally run Ray from, please?

**Comment by ilonadem** [comment]
@mfitton Ok, sorry about that -- I wasn't running things in root. I ran everything as root and the psutil issues got resolved. My dashboard is still blank though, and looks like this:
![image](https://user-images.githubusercontent.com/69218138/90190240-a3b61300-dd8c-11ea-984c-f603ed0c74aa.png)
The dashboard.err file reads: 
``` UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0813 17:39:24.779670 70281 70281 global_state_accessor.cc:25] Redis server address = 172.23.49.92:43815, is test flag = 0
I0813 17:39:24.781157 70281 70281 redis_client.cc:141] RedisClient connected.
I0813 17:39:24.789605 70281 70281 redis_gcs_client.cc:88] RedisGcsClient Connected.
I0813 17:39:24.791425 70281 70281 service_based_gcs_client.cc:75] ServiceBasedGcsClient Connected.
2020-08-13 17:39:24,814 INFO node_stats.py:179 -- NodeStats: subscribed to RAY_REPORTER.*
2020-08-13 17:39:24,814 INFO node_stats.py:183 -- NodeStats: subscribed to RAY_LOG_CHANNEL
2020-08-13 17:39:24,815 INFO node_stats.py:187 -- NodeStats: subscribed to 9
2020-08-13 17:39:24,815 INFO node_stats.py:191 -- NodeStats: subscribed to b'ACTOR:*'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/grid/common/pkgs/python/v3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "<redacted directory>/.virtualenv/lib/python3.7/site-packages/ray/dashboard/node_stats.py", line 208, in run
    for x in p.listen():
  File "<redacted directory>/.virtualenv/lib/python3.7/site-packages/redis/client.py", line 3553, in listen
    response = self.handle_message(self.parse_response(block=True))
  File "<redacted directory>/.virtualenv/lib/python3.7/site-packages/redis/client.py", line 3453, in parse_response
    response = self._execute(conn, conn.read_response)
  File "<redacted directory>/.virtualenv/lib/python3.7/site-packages/redis/client.py", line 3427, in _execute ```
When I run
``` ray stack```
I get:
``` Stack dump for demler    72086  1.7  0.0 2464016 63300 pts/10  Sl   17:43   0:01 <redacted directory>/.virtualenv/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2020-08-13_17-43-39_252589_72063/sockets/raylet --store_socket_name=/tmp/ray/session_2020-08-13_17-43-39_252589_72063/sockets/plasma_store --object_manager_port=0 --min_worker_port=10000 --max_worker_port=10999 --node_manager_port=52253 --node_ip_address=172.23.49.92 --redis_address=172.23.49.92 --redis_port=6379 --num_initial_workers=56 --maximum_startup_concurrency=56 --static_resource_list=node:172.23.49.92,1.0,CPU,56,memory,3331,object_store_memory,1041 --config_list= --python_worker_command=<redacted directory>/.virtualenv/bin/python3.7 /<redacted directory>/.virtualenv/lib/python3.7/site-packages/ray/workers/default_worker.py --node-ip-address=172.23.49.92 --node-manager-port=52253 --object-store-name=/tmp/ray/session_2020-08-13_17-43-39_252589_72063/sockets/plasma_store --raylet-name=/tmp/ray/session_2020-08-13_17-43-39_252589_72063/sockets/raylet --redis-address=172.23.49.92:6379 --config-list= --temp-dir=/tmp/ray --redis-password=5241590000000000 --java_worker_command= --redis_password=5241590000000000 --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2020-08-13_17-43-39_252589_72063
Error: Failed to find python version from target process ```

**Comment by mfitton** [comment]
Hmm, the issue could be that "172.23.49.92:43815" (the redis address that Ray is trying to connect to), is not accessible from that machine? Essentially, the dashboard collects details about the worker processes running on each other node in the cluster over Redis. This means that you will need to give the same permissions for psutil on other nodes in the cluster, as well as make sure that your head node is able to connect to your redis cluster. The `redis.out` and `redis.err` log files might also be helpful.

**Comment by ilonadem** [comment]
@mfitton I see. So far I've just been starting my head node and trying to view the ray dashboard on the same server, so I am unclear why permissions might be different for My redis.err file is empty, but the redis.out file has:

```71208:C 17 Aug 2020 09:15:31.250 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
71208:C 17 Aug 2020 09:15:31.250 # Redis version=5.0.9, bits=64, commit=00000000, modified=0, pid=71208, just started
71208:C 17 Aug 2020 09:15:31.250 # Configuration loaded
71208:M 17 Aug 2020 09:15:31.252 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
71208:M 17 Aug 2020 09:15:31.252 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
71208:M 17 Aug 2020 09:15:31.252 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
71208:M 17 Aug 2020 09:15:31.252 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.71208:M 17 Aug 2020 09:15:31.252 # Server initialized
71208:M 17 Aug 2020 09:15:31.252 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
71208:M 17 Aug 2020 09:15:31.252 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
