### ISSUE TITLE
Docker builds failing on 1.10.0rc0 release branch

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#21400]
Example: https://buildkite.com/ray-project/ray-builders-branch/builds/5398#85c463c1-9bb3-4248-b3ae-12c445abcec4/6-8426

```
Traceback (most recent call last):
  File "./ci/travis/build-docker-images.py", line 677, in <module>
    and is_merge)
  File "./ci/travis/build-docker-images.py", line 407, in push_and_tag_images
    _get_branch()).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by architkulkarni** [comment]
It looks like this is the offending part:

https://github.com/ray-project/ray/blob/853d10871c55cb741cb15212ef4ab42f158f968c/ci/travis/build-docker-images.py#L406-L407

I can see how this might suddenly break for 1.10 when it worked up to 1.9, let me think about how to fix this.

**Comment by ijrsvt** [comment]
Let me open a PR reql quick

**Comment by architkulkarni** [comment]
Seems like it didn't quite work on the `1.10.0rc0` branch, any ideas about this @ijrsvt? 

https://buildkite.com/ray-project/ray-builders-branch/builds/5415#5639718e-d3bf-4863-8756-50e617e57499/6-8426

Same error: 
```
Traceback (most recent call last):
--
  | File "./ci/travis/build-docker-images.py", line 677, in <module>
  | and is_merge)
  | File "./ci/travis/build-docker-images.py", line 407, in push_and_tag_images
  | _get_branch()).group(0)
  | AttributeError: 'NoneType' object has no attribute 'group'
```
