### ISSUE TITLE
[Bug] Ray sample_batch crashed with tensorflow v1 installed

### ISSUE THREAD

**Issue by SoloGao** [ray-project/ray#21210]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

When TensorFlow v1 installed, ray/rllib/policy/sample_batch.py inits failed with "AttributeError: module 'tensorflow' has no attribute 'is_tensor'"

It is because https://github.com/ray-project/ray/blob/d1a27487a359f8721b0913f9989fe624bbc46195/rllib/policy/sample_batch.py#L119 referenced tf without check tfv, however, there's no tf.is_tensor in tf1. 

### Versions / Dependencies

TensorFlow 1.9.0
Ray 1.9.0

### Reproduction script

trainer = ppo.PPOTrainer(config=ppo_config, env=Environment)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sven1977** [comment]
Actually, thinking about this, @SoloGao we don't support old tf versions like 1.9.0 (are you sure you didn't mix up ray and tf versions above :) ). tf1.9 doesn't even have the compat.v1 package and I'm getting another error:
```
AttributeError: module 'tensorflow.compat' has no attribute 'v1'
```

Your repro script works fine on tf1.15 (which is what we use in our CI-tests (actually tf1.14) to make sure we keep tf1.x compatible at least from tf1.14 up).

Will close this issue now. Sorry, but you will have to upgrade to a newer tf version for RLlib to work. Will update the documentation to make sure this is mentioned in there.
