### ISSUE TITLE
Failure to checkpoint PPO agent.

### ISSUE THREAD

**Issue by robertnishihara** [ray-project/ray#982]
Steps to reproduce. Looks like this was introduced in #965.

```python
import ray
from ray.rllib.ppo import PPOAgent, DEFAULT_CONFIG

ray.init(num_workers=0)

agent = PPOAgent('Pong-v0', DEFAULT_CONFIG)
agent.save()
```

This gives the following error.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-4c879b9f1898> in <module>()
      5 
      6 agent = PPOAgent('Pong-v0', DEFAULT_CONFIG)
----> 7 agent.save()

~/Workspace/ray/python/ray/rllib/common.py in save(self)
    171         pickle.dump(
    172             [self.experiment_id, self.iteration, self.timesteps_total,
--> 173              self.time_total_s],
    174             open(checkpoint_path + ".rllib_metadata", "wb"))
    175         return checkpoint_path

AttributeError: 'PPOAgent' object has no attribute 'time_total_s'
```

cc @ericl

**Comment by robertnishihara** [comment]
Fixed by #988.
