### PR TITLE
Adapt Dask on Ray to the new Dask Task class

### LINKED ISSUE #48689: [Util] Cannot import Dask scheduler
### What happened + What you expected to happen

One of the latest Dask releases (`v2024.11.0`) removed the `_execute_task` method from its core module in favor of `execute_graph` (https://github.com/dask/dask/commit/a0783a8d46ffa0203906c47c7495a7e5bc09e691). The dask on ray scheduler implementation currently needs it:
https://github.com/ray-project/ray/blob/3141dfe4031cc715515b365278cd1d6b8955154e/python/ray/util/dask/scheduler.py#L12-L12

This behavior was detected in a [smoke test ](https://github.com/astronomy-commons/hats-import/actions/runs/11773574682/job/32790700118) run for `hats-import`.

```
ImportError while loading conftest '/home/runner/work/hats-import/hats-import/tests/conftest.py'.
tests/conftest.py:8: in <module>
    from ray.util.dask import disable_dask_on_ray, enable_dask_on_ray
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/ray/util/dask/__init__.py:2: in <module>
    from .scheduler import (
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/ray/util/dask/scheduler.py:12: in <module>
    from dask.core import istask, ishashable, _execute_task
E   ImportError: cannot import name '_execute_task' from 'dask.core' (/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/dask/core.py)
```

### Versions / Dependencies

ray==2.38.0
dask==2024.11.1
dask-expr==1.1.18
distributed==2024.11.1

### Reproduction script

```python
from ray.util.dask import disable_dask_on_ray, enable_dask_on_ray
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by HiromuHota**
## Why are these changes needed?
"Dask on Ray" (DoR) is broken in dask==2024.11.0 or later as reported in https://github.com/ray-project/ray/issues/48689 because Dask removed a private function in https://github.com/dask/dask/pull/11378 that DoR has been relying on. Not only https://github.com/dask/dask/pull/11378, Dask has migrated their task data structure to a new format (the high-level motivation is described in https://github.com/dask/dask/issues/9969). Since this migration spans across a series of PRs between 2024.11.0 and 2025.1.0, it's not realistic to copy what's been removed and paste them in Ray.

This PR adapts Dask on Ray to the change to keep its functionality.
The current PR as of 7c9def3 is compatible only with `dask>=2024.11.0,<2025.1.0` because Dask made another major change in 2025.1.0, breaking the shuffle optimization introduced in https://github.com/ray-project/ray/pull/13951.
I can make further changes in this PR if we want to support `dask>=2025.1.0` and drop support `dask<2025.1.0`. Supporting both would technically be possible but that would make codebase complicated. Let me know how Ray would like to approach this.

## Related issue number

Closes #48689

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a
           method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by HiromuHota** [comment]
Since CI doesn't run unit tests with a newer version of dask, this is the result of unit tests that I locally ran.
```
(ray) ubuntu@ip-10-1-24-215:~/workspace/ray/python$ python -m pytest ray/util/dask/tests
Test session starts (platform: linux, Python 3.10.12, pytest 7.4.4, pytest-sugar 0.9.5)
rootdir: /home/ubuntu/workspace/ray
configfile: pytest.ini
plugins: aiohttp-0.3.0, shutil-1.7.0, virtualenv-1.7.0, fugue-0.8.7, timeout-2.1.0, typeguard-2.13.3, forked-1.4.0, httpserver-1.0.6, sphinx-0.5.1.dev0, lazy-fixture-0.6.3, docker-tools-3.1.3, sugar-0.9.5, repeat-0.9.3, asyncio-0.17.0, mock-3.14.0, rerunfailures-11.1.2, remotedata-0.3.2, anyio-3.7.1
timeout: 180.0s
timeout method: signal
timeout func_only: False
collecting ... 
 python/ray/util/dask/tests/test_dask_callback.py ✓✓✓✓✓✓✓✓                                                                                                            57% █████▊    
 python/ray/util/dask/tests/test_dask_optimization.py ✓✓                                                                                                              71% ███████▎  
 python/ray/util/dask/tests/test_dask_scheduler.py ✓✓✓✓                                                                                                              100% ██████████

Results (60.70s):
      14 passed
(ray) ubuntu@ip-10-1-24-215:~/workspace/ray/python$ pip list | grep dask
dask                                   2024.12.0
```

**Comment by HiromuHota** [comment]
@robertnishihara 

I think it'd be safer for Dask on Ray users to phase the migration because of the changes in Dask side:
1.  Dask introduced another major change in 2025.1.0 that removed the legacy Dask Dataframe implementation and fully switched to the new one ([release note](https://docs.dask.org/en/stable/changelog.html#legacy-dask-dataframe-implementation-removed)). There would be an inherent risk due to this major change.
2. The shuffle optimization, introduced in https://github.com/ray-project/ray/pull/13951, that I mentioned in the description was broken by this removal. I'm not sure if it is worth fixing it because Dask introduced a better shuffling method "p2p" in 2023 ([blog](https://docs.coiled.io/blog/better-shuffling-in-dask-a-proof-of-concept.html)), meanwhile #13951 was done in 2021 to solve #13959, by making the complexity of N^2 into N and the newer shuffling "p2p" addressed the same problem. This indicates that the custom optimization for Dask on Ray in https://github.com/ray-project/ray/pull/13951 is no longer relevant and Dask on Ray users can benefit from Dask's optimization for free.

So, I'd suggest to split the migration into two: ship this PR as is, wait Ray to be released at least once (e.g., 2.44.2), and then do another migration without https://github.com/ray-project/ray/pull/13951 to be released in a later version of Ray. This way, it'd be easier to identify the root cause if some issue happens.

**Comment by rbavery** [comment]
Just my own two cents, but I think that Dask-on-ray has been in a quasi maintained state long enough that I don't think many (or any?) are using it in production. So I think it is safe to optimize for the latest version. Selfishly, we are keen to use the latest version of Dask and try Dask on Ray with it. There's been some crucial optimizations made after 2025.1.0

https://docs.dask.org/en/stable/changelog.html#reducing-memory-pressure-for-xarray-workloads
https://docs.dask.org/en/stable/changelog.html#automatically-adjust-chunksizes-in-xarray-apply-ufunc

However I'm just happy that this is seeing some activity again and looking forward to trying whenever it is available.

**Comment by HiromuHota** [comment]
I made a further change to support dask>=2025.1.0.
As of https://github.com/ray-project/ray/pull/52589/commits/f8fe6866a2a5a57b43f21174334e79c5ffddc6c4, the support matrix looks like this:

| dask | dask_expr | Dask on Ray |
| --- | --- | --- |
| <2024.11.0 | N/A | No |
| >=2024.11.0,<2025.1.0 | Not installed | Yes |
| >=2024.11.0,<2025.1.0 | Installed | Yes w/o custom optimization |
| >=2025.1.0 | N/A | Yes w/o custom optimization |

**Comment by richardliaw** [comment]
generally this looks great! seems like tests are failing though?

**Comment by HiromuHota** [comment]
oh no, since dask>=2024.8.1, Dask requires cloudpickle >= 3.0.0 https://github.com/dask/dask/pull/11320. @richardliaw Would that be possible to upgrade cloudpickle?

**Comment by richardliaw** [comment]
> Would that be possible to upgrade cloudpickle?

@aslonnie is that something you can help with?

**Comment by aslonnie** [comment]
> > Would that be possible to upgrade cloudpickle?
> 
> @aslonnie is that something you can help with?

this is complicated.. cloudpickle is a dependency of not only dask, but also

````
dask
distributed
gymnasium
hyperopt
mlagents-envs
mlflow
pymars
statsforecast
tensorflow-probability
````

**Comment by aslonnie** [comment]
I tried upgraded some of the ones mentioned:

https://github.com/ray-project/ray/pull/52961

but failed

I think it will either require us stop supporting older versions of pyarrow and pandas, or needs to build a more powerful solution for managing dependencies..

**Comment by aslonnie** [comment]
cc @elliot-barn 

it might require quite some heavy-lifting to make it happen.

**Comment by HiromuHota** [comment]
> I tried upgraded some of the ones mentioned:
> 
> #52961
> 
> but failed
> 
> I think it will either require us stop supporting older versions of pyarrow and pandas, or needs to build a more powerful solution for managing dependencies..

I saw #52961 and the tests that failed. All of the failed tests were Dask on Ray, which are fixed in this PR. If we can combine the two, we can go forward?

**Comment by aslonnie** [comment]
> All of the failed tests were Dask on Ray, which are fixed in this PR. If we can combine the two, we can go forward?

we can give it a try.. you are free to change the dependencies on this PR, or take files from https://github.com/ray-project/ray/pull/52961 and see how tests go.

@richardliaw could you help loop in some one from data team on this too?

----

I am not sure if all of the failed tests are dask related. for example this error:

https://buildkite.com/ray-project/premerge/builds/39719#0196c8b2-3802-4d81-8f90-0cc52fbc7fcb/178-2830

````
[2025-05-13T08:40:54Z] E           ImportError: pyarrow>=10.0.1 is required for ArrowDtype
````

I am not sure how it was not failing before the dependency change though..

**Comment by aslonnie** [comment]
For updating dependencies, the easy but a bit time-consuming way is to look at the `pip-compile` test job, like this one:

https://buildkite.com/ray-project/microcheck/builds/16384#0196d742-a3ac-40ff-b589-c74f9b3ca18d

and copy out the file from the job's artifact and overwrite the file in the repo.

a faster way is to get a linux amd64 machine with conda+python 3.11, and run `bash ci/ci.sh compile_pip_dependencies`, which will update the `requirements_compiled.txt` file locally.

**Comment by aslonnie** [comment]
the `requirements_compiled.txt` is a dependency resolution result from the set of requirement constraint files as inputs (`python/requirements.txt` and other files under `python/requirements/`)

there are other nuances here and there, but if you got a version of `requirements_compiled.txt` file that can:

1. satisfies the `pip-compile` test, which tests all the constraints
2. make all related python tests happy too

it will be a big milestone, and the rest is often simple.

----

what I worry is that there are tests that fundamentally depends on package versions that have conflicts, where the single `requirements_compiled.txt` has to be split to move things forward.

**Comment by HiromuHota** [comment]
`ModuleNotFoundError: No module named 'path'` appeared in "core: python tests [g4_s5]" since https://github.com/ray-project/ray/pull/52589/commits/0e38343bf74ee7341b56a8336816da48d50e3694 probably due to the removal of `path==16.14.0` in that commit.

**Comment by HiromuHota** [comment]
```
[2025-05-17T21:53:23Z] #10 413.2 The conflict is caused by:
--
  | [2025-05-17T21:53:23Z] #10 413.2     dask[array,dataframe,diagnostics,distributed] 2025.5.0 depends on bokeh>=3.1.0; extra == "diagnostics"
  | [2025-05-17T21:53:23Z] #10 413.2     The user requested (constraint) bokeh==2.4.3
```
in wanda: mlgpubuild-py3.12 https://buildkite.com/ray-project/microcheck/builds/16496#0196e026-f0b3-41dc-a03c-6efb64dc1b82

File: python/ray/data/dataset.py [hunk 1]
```diff
@@ -5245,20 +5245,14 @@ def to_dask(
...
         def block_to_df(block_ref: ObjectRef[Block]) -> pd.DataFrame:
-            if isinstance(block_ref, (ray.ObjectRef, ClientObjectRef)):
-                raise ValueError(
-                    "Dataset.to_dask() must be used with Dask-on-Ray, please "
-                    "set the Dask scheduler to ray_dask_get (located in "
-                    "ray.util.dask)."
-                )
-            return _block_to_df(block_ref)
+            block = ray.get(block_ref)
+            return _block_to_df(block)
```
Comment (HiromuHota) [inline python/ray/data/dataset.py:5255]: Let me double-check the right behavior.

**Comment by HiromuHota** [comment]
doc tests complains `NameError: name 'convert_legacy_graph' is not defined` https://buildkite.com/ray-project/microcheck/builds/16516#0196e46f-0537-4620-a66d-8f64f9abed7a. Assuming doc tests use python 3.11, seems like we should use a more recent version of dask in python 3.11.

File: python/ray/data/dataset.py (hunk 1 above)
Comment (HiromuHota) [reply python/ray/data/dataset.py]: Reworked in https://github.com/ray-project/ray/pull/52589/commits/ed174252a5045662a6ccb55a757f8e6ce657f7b8

**Comment by HiromuHota** [comment]
> doc tests complains `NameError: name 'convert_legacy_graph' is not defined` https://buildkite.com/ray-project/microcheck/builds/16516#0196e46f-0537-4620-a66d-8f64f9abed7a. Assuming doc tests use python 3.11, seems like we should use a more recent version of dask in python 3.11.

Turned out that doc tests run on python 3.9. Let me revert back to https://github.com/ray-project/ray/pull/52589/commits/ed174252a5045662a6ccb55a757f8e6ce657f7b8, which has an issue only at doc tests.

**Comment by HiromuHota** [comment]
As of https://github.com/ray-project/ray/pull/52589/commits/e7037f35ea600352b1c5987036b415def1468d46, all but the doc test passed.
Based on https://buildkite.com/ray-project/microcheck/builds/16623, it seems that Ray uses python 3.9 during doc tests, which is no longer supported by Dask and by Dask on Ray because 2024.8.0 is the last version of dask supported in 3.9 and the new Dask on Ray is compatible with 2024.11.0 or later (https://github.com/ray-project/ray/pull/52589#issuecomment-2869040468).

@richardliaw or @aslonnie
1. (my recommendation) Is it possible to upgrade the python version from 3.9 to 3.10 or later during the doc tests?
2. If not, then can we skip them during the doc tests?

**Comment by richardliaw** [comment]
@aslonnie it'd be great to upgrade doctests to py3.12; but I also think we can unblock this PR by disabling the doctest for this for now.

**Comment by aslonnie** [comment]
> @aslonnie it'd be great to upgrade doctests to py3.12; but I also think we can unblock this PR by disabling the doctest for this for now.

we can split the ones that need to run on py312 to run on py312.

most of the doc tests will still need to run on py39.

**Comment by aslonnie** [comment]
hi @HiromuHota , after some internal discussion, here is a proposed plan:

- we would like to just mark python 3.9 as not supported for dask-ray integration. essentially, when it is python 3.9, instead of trying to import dask in ray code, we will just throw an exception
- as a result, we will just use a version that support python 3.10+

if you think it is okay, please confirm, and I will help you resolve the dependency stuff and set up the related CI jobs.

I probably need some of your help to understand where is the best place to throw an "py3.9 not supported" exception.

**Comment by HiromuHota** [comment]
@aslonnie Thank you for the discussion and the proposal, which sounds good to me!

> where is the best place to throw an "py3.9 not supported" exception.

We can just check the version of Dask (should be dask>=2024.11.0) rather than checking Python version. Python 3.9 can't install any version later than 2024.8.0 anyway.
`python/ray/util/dask/__init__.py` would be the best place to throw such an error because the main interface (enable_dask_on_ray & ray_dask_get), documented in https://docs.ray.io/en/latest/ray-more-libs/dask-on-ray.html, is imported from `ray.util.dask`. Let me add this.

File: python/ray/util/dask/tests/test_dask_callback.py [hunk 2]
```diff
@@ -9,7 +9,7 @@
 from ray.util.dask import ray_dask_get, RayDaskCallback
 
 pytestmark = pytest.mark.skipif(
-    sys.version_info >= (3, 12), reason="Skip dask tests for Python version 3.12+"
+    sys.version_info < (3, 12), reason="Skip dask tests for Python version < 3.12"
```
Comment (aslonnie) [inline python/ray/util/dask/tests/test_dask_callback.py]: do we want to make it testable on python 3.10?

or more broadly, does the code being written here works when it is running python 3.10?

it is okay for us to drop py3.9, but I am not sure if we would like to also drop py3.10 and 3.11 and only supports py3.12.

Comment (HiromuHota) [reply python/ray/util/dask/tests/test_dask_callback.py]: Nice catch!
The tests written here work with python 3.10 and later as long as dask is >=2024.11.0.
I couldn't get rid of this version check because of the dependency hell.

Comment (HiromuHota) [reply python/ray/util/dask/tests/test_dask_callback.py]: Let me go ahead and get rid of this.

Comment (HiromuHota) [reply python/ray/util/dask/tests/test_dask_callback.py]: Removed.

**Comment by robertnishihara** [comment]
Definitely not stale. @HiromuHota @richardliaw @aslonnie let's just chat live to get it merged.

**Comment by aslonnie** [comment]
I will address this after I get the other release blocking CI issues fixed.

**Comment by aslonnie** [comment]
> I will address this after I get the other release blocking CI issues fixed.

or if any one has cycle to help, I am happy to give specific instructions.. :)

**Comment by HiromuHota** [comment]
Thank you for your help @aslonnie !! Let me know if there is anything I can help!

**Comment by aslonnie** [comment]
> Thank you for your help @aslonnie !! Let me know if there is anything I can help!

first, @HiromuHota sorry for the all the delay. juggling among many stuff.

hate to ask, but could you sync down `lonnie-250725-daskup` branch (my dev branch), and help fix the doc build (the `api_policy_check` check, which builds the doc).

I am not 100% sure, but I guess one possible fix is to wrap the dask version exception throwing with `if not TYPE_CHECKING:`. or maybe there are also other issues.

you can time box it to maybe several hours, and if not able to figure it out, you can leave it back to me.

**Comment by HiromuHota** [comment]
@aslonnie sure thing! Let me take a look over the weekend.

**Comment by HiromuHota** [comment]
@aslonnie With e5bac7788ec4e0aa9f68b6098a42aa9b775e452b, the doc test now has passed.

**Comment by aslonnie** [comment]
@HiromuHota thanks for fixing the docs issue.

I managed to split the dask doc tests out and run on py312, but one of the test is failing due to the following error:

https://buildkite.com/ray-project/premerge/builds/42766#0197bb99-4ce1-4822-8760-fad62d9c3c2e/178-965

````
[2025-06-29T12:33:30Z] Traceback (most recent call last):
--
  | [2025-06-29T12:33:30Z]   File "/root/.cache/bazel/_bazel_root/1df605deb6d24fc8068f6e25793ec703/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin/doc/source/ray-more-libs/doc_code/dask_on_ray_persist_example.runfiles/com_github_ray_project_ray/doc/source/ray-more-libs/doc_code/dask_on_ray_persist_example.py", line 15, in <module>
  | [2025-06-29T12:33:30Z]     print(dask.base.collections_to_dsk([d_arr]))
  | [2025-06-29T12:33:30Z]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | [2025-06-29T12:33:30Z] AttributeError: module 'dask.base' has no attribute 'collections_to_dsk'. Did you mean: 'collections_to_expr'?
````

could you advise how to fix it?

**Comment by HiromuHota** [comment]
@aslonnie 

`dask.base.collections_to_dsk` has been renamed to `collections_to_expr` in dask==2025.4.0 (https://docs.dask.org/en/stable/changelog.html#v2025-4-0).

**Comment by aslonnie** [comment]
> @aslonnie
> 
> `dask.base.collections_to_dsk` has been renamed to `collections_to_expr` in dask==2025.4.0 (https://docs.dask.org/en/stable/changelog.html#v2025-4-0).

then how to update this example:

````
d_arr = da.ones(100)
print(dask.base.collections_to_expr([d_arr]))
# {('ones-c345e6f8436ff9bcd68ddf25287d27f3',
#   0): (functools.partial(<function _broadcast_trick_inner at 0x7f27f1a71f80>,
#   dtype=dtype('float64')), (5,))}
````

it does not return a dict anymore (but an `Expr`), and it needs to be materialized?

**Comment by aslonnie** [comment]
code point link of the example:

https://github.com/ray-project/ray/blob/b77775cd5f72911aa77bfe6e81e5b1712371ce09/doc/source/ray-more-libs/doc_code/dask_on_ray_persist_example.py#L15

this seems to be the only failing thing for this change now.

**Comment by HiromuHota** [comment]
@aslonnie I think we can just replace `collections_to_dsk` with `collections_to_expr` but 
1. I don't think this is good because `collections_to_expr` is only available dask=>2025.4.0
2. More importantly, seems like I missed to update this feature https://docs.ray.io/en/latest/ray-more-libs/dask-on-ray.html#persist (or #14294). Just replacing `collections_to_dsk` with `collections_to_expr` would fail with `numpy.exceptions.AxisError: axis 0 is out of bounds for array of dimension 0`. Can you confirm?

Let me look into this.

**Comment by aslonnie** [comment]
> Let me look into this.

you can take all my changes in https://github.com/ray-project/ray/pull/54108 , where the dask doc test is the only test that is failing.

**Comment by HiromuHota** [comment]
> > Let me look into this.
> 
> you can take all my changes in #54108 , where the dask doc test is the only test that is failing.

Yeah, I can see the same error that I got locally in the failing doc test.
```
numpy.exceptions.AxisError: axis 0 is out of bounds for array of dimension 0
```

**Comment by HiromuHota** [comment]
@aslonnie The premerge test now passed. Anything else I can help?

File: python/requirements/test-requirements.txt [hunk 3]
```diff
@@ -54,7 +57,8 @@ pytest-rerunfailures==11.1.2
 pytest-sugar==0.9.5
 pytest-lazy-fixtures==1.1.2
 pytest-timeout==2.1.0
-pytest-virtualenv==1.7.0; python_version < "3.12"
+pytest-virtualenv==1.8.1; python_version < "3.12"
+pytest-shutil==1.8.1; python_version < "3.12"
```
Comment (aslonnie) [inline python/requirements/test-requirements.txt]: could you remove this `pytest-shutil` line? this is not directly being used.

**Review by aslonnie — COMMENTED** [review]
nice job and looks good. could you fix the DCO (squash and use `git commit -s` to add your signature).

or alternatively, I can also just take your change and merge it in for you.

**Comment by HiromuHota** [comment]
> nice job and looks good. could you fix the DCO (squash and use `git commit -s` to add your signature).
> 
> or alternatively, I can also just take your change and merge it in for you.

uh, I struggled to squash your commits.
As long as a credit like `Co-authored-by: Hiromu Hota <hiromu.hota@gmail.com>` or something equivalent is included in the squashed commit, the alternative sounds like a charm to me.

**Comment by aslonnie** [comment]
ok, I will squash it and merge it for you.

File: python/ray/util/dask/tests/test_dask_multi_node.py [hunk 4]
```diff
@@ -67,6 +66,39 @@ def get_node_id():
...
+    # with dask.annotate(ray_remote_args=dict(num_cpus=1, resources={"pin": 0.01})):
+    #     df = dd.from_pandas(
+    #         pd.DataFrame(
+    #             np.random.randint(0, 2, size=(2, 2)), columns=["age", "grade"]
+    #         ),
+    #         npartitions=2,
+    #     )
+    #     c = df.apply(get_node_id, axis=1, meta={"id": str})
+    # result = c.compute(optimize_graph=False)
+    # assert result[0].iloc[0] == pinned_node.unique_id
```
Comment (aslonnie) [inline python/ray/util/dask/tests/test_dask_multi_node.py:83]: @HiromuHota can we remove this code section that is commented out? or does this actually serve some purpose?

**Comment by aslonnie** [comment]
hi @HiromuHota , your changes are all merged in https://github.com/ray-project/ray/pull/54108

I am closing this PR now.

**Comment by HiromuHota** [comment]
@aslonnie Thank you so much for your help! This is so exciting!
