### ISSUE TITLE
[Ray component: Tune] Importing TuneBOHB breaks in Python 3.8 

### ISSUE THREAD

**Issue by meechos** [ray-project/ray#35264]
### What happened + What you expected to happen

Importing the TuneBOHB search breaks with an error. This happens in Python 3.8 but works fine in Python 3.6. 

### Versions / Dependencies

- python 3.8
- ray 2.3.0
- numpy 1.24.3 OR 1.19.5

Of note, configspace latest list version on `pip 0.4.16 `and on `conda 0.4.19`, however they mention that the latest release is `0.6`.

#### W/ numpy >1.20 && ConfigSpace==0.4.16:
```python
(py38) cdsw@4gtkrv0fc4jkcm7a:~$ python3
Python 3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from ray.tune.search.bohb import TuneBOHB
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/search/bohb/__init__.py", line 1, in <module>
    from ray.tune.search.bohb.bohb_search import BOHB, TuneBOHB
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/search/bohb/bohb_search.py", line 33, in <module>
    import ConfigSpace
  File "/home/cdsw/.local/lib/python3.8/site-packages/ConfigSpace/__init__.py", line 37, in <module>
    from ConfigSpace.configuration_space import Configuration, \
  File "ConfigSpace/configuration_space.pyx", line 57, in init ConfigSpace.configuration_space
  File "ConfigSpace/c_util.pyx", line 11, in init ConfigSpace.c_util
  File "/home/cdsw/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing thiswill not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

#### W/ numpy==1.19.5 && ConfigSpace==0.4.16:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/__init__.py", line 2, in <module>
    from ray.tune.tune import run_experiments, run
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/tune.py", line 14, in <module>
    from ray.tune.analysis import ExperimentAnalysis
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/analysis/__init__.py", line 1, in <module>
    from ray.tune.analysis.experiment_analysis import ExperimentAnalysis
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/analysis/experiment_analysis.py", line 32, in <module>
    from ray.tune.experiment import Trial
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/experiment/__init__.py", line 2, in <module>
    from ray.tune.experiment.trial import Trial
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/experiment/trial.py", line 44, in <module>
    from ray.tune.trainable.util import TrainableUtil
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/trainable/__init__.py", line 1, in <module>
    from ray.tune.trainable.trainable import Trainable
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/trainable/trainable.py", line 48, in <module>
    from ray.tune.trainable.util import TrainableUtil
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/trainable/util.py", line 9, in <module>
    import pandas as pd
  File "/home/cdsw/.local/lib/python3.8/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401  File "/home/cdsw/.local/lib/python3.8/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/home/cdsw/.local/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py", line 24, in <module>
    raise ImportError(
ImportError: this version of pandas is incompatible with numpy < 1.20.3
your numpy version is 1.19.0.
Please upgrade numpy to >= 1.20.3 to use this pandas version
```
#### W/ numpy >1.20 && ConfigSpace==0.4.19:

```python
>>> from ray.tune.search.bohb import TuneBOHB
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/search/bohb/__init__.py", line 1, in <module>
    from ray.tune.search.bohb.bohb_search import BOHB, TuneBOHB
  File "/home/cdsw/.local/lib/python3.8/site-packages/ray/tune/search/bohb/bohb_search.py", line 34, in <module>
    from hpbandster.optimizers.config_generators.bohb import BOHB
  File "/home/cdsw/.local/lib/python3.8/site-packages/hpbandster/optimizers/__init__.py", line 3, in <module>
    from hpbandster.optimizers.bohb import BOHB
  File "/home/cdsw/.local/lib/python3.8/site-packages/hpbandster/optimizers/bohb.py", line 14, in <module>
    from hpbandster.optimizers.config_generators.bohb import BOHB as CG_BOHB
  File "/home/cdsw/.local/lib/python3.8/site-packages/hpbandster/optimizers/config_generators/bohb.py", line 10, in <module>
    import scipy.stats as sps
  File "/home/cdsw/.local/lib/python3.8/site-packages/scipy/stats/__init__.py", line 384, in <module>
    from .stats import *
  File "/home/cdsw/.local/lib/python3.8/site-packages/scipy/stats/stats.py", line 179, in <module>
    from scipy.spatial.distance import cdist
  File "/home/cdsw/.local/lib/python3.8/site-packages/scipy/spatial/__init__.py", line 97, in <module>
    from .kdtree import *
  File "/home/cdsw/.local/lib/python3.8/site-packages/scipy/spatial/kdtree.py", line 8, in <module>
    import scipy.sparse
  File "/home/cdsw/.local/lib/python3.8/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/home/cdsw/.local/lib/python3.8/site-packages/scipy/sparse/base.py", line 8, in <module>
    from .sputils import (isdense, isscalarlike, isintlike,
  File "/home/cdsw/.local/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 17, in <module>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/home/cdsw/.local/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 17, in <listcomp>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/home/cdsw/.local/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by woshiyyya** [comment]
Hey @meechos, how did you install ray tune? Did you use `pip install -U "ray[tune]"` or `conda install -c conda-forge "ray-tune"`?

**Comment by meechos** [comment]
I think you are correct. Closing for now as I think this resolved the issue, thank you @woshiyyya.
